"""
E2E test conftest for Memoria.

Strategy
────────
Each test session spins up a real uvicorn server against a temp books_dir
pre-seeded with two small Memory Bank .md files and a tiny sample_project/
directory. litellm.completion is monkeypatched to return deterministic
streaming SSE responses so no API keys are needed.

The ChromaDB index is built from the seeded books at session start so
semantic search works out-of-the-box.

Fixtures
────────
  books_dir          — temp dir pre-seeded with 2 Memory Banks
  sample_project_dir — 3 small Python files that can be analyzed
  config_file        — minimal config.yaml
  live_server        — real uvicorn on a random port; yields base URL + books_dir
  http_client        — httpx.AsyncClient pointed at the live server

Usage
─────
  pytest tests/e2e/                 # run all e2e tests
  pytest tests/e2e/ -k test_chat    # run one file
  pytest tests/e2e/ -v              # verbose

Requirements
────────────
  pip install -r requirements-dev.txt
"""

import json
import textwrap
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock, patch

import pytest
import httpx


# ── Deterministic mock LLM responses ─────────────────────────────────────────

_MOCK_BOOK_AUTH = textwrap.dedent("""\
    # auth-service — Memory Bank
    > Last updated: 2026-01-01 | Generated by Memoria (test)

    ## TL;DR
    - Handles authentication via JWT tokens and OAuth2
    - FastAPI backend, Python 3.11
    - Rate limit: 100 requests/second

    ## Architecture
    Single FastAPI app with JWT middleware.
    Endpoints: /login, /logout, /refresh, /me

    ## Tech Stack
    Python, FastAPI, JWT, OAuth2, Redis (session store)

    ## Key Components
    `auth/routes.py` — login/logout endpoints
    `auth/jwt.py` — token generation and validation
    `auth/middleware.py` — request authentication check
""")

_MOCK_BOOK_PAYMENTS = textwrap.dedent("""\
    # payments-service — Memory Bank
    > Last updated: 2026-01-01 | Generated by Memoria (test)

    ## TL;DR
    - Processes card payments via Stripe
    - Depends on auth-service for user identity
    - PostgreSQL for transaction records

    ## Architecture
    FastAPI service calling Stripe API.
    Webhooks for async payment events.

    ## Tech Stack
    Python, FastAPI, Stripe, PostgreSQL, SQLAlchemy

    ## Key Components
    `payments/routes.py` — charge and refund endpoints
    `payments/stripe_client.py` — Stripe SDK wrapper
    `payments/models.py` — Transaction ORM model
""")

_SAMPLE_PY_MAIN = textwrap.dedent("""\
    # sample_project/main.py
    from fastapi import FastAPI
    app = FastAPI()

    @app.get("/")
    def root():
        return {"status": "ok"}
""")

_SAMPLE_PY_MODELS = textwrap.dedent("""\
    # sample_project/models.py
    from pydantic import BaseModel

    class Item(BaseModel):
        id: int
        name: str
        active: bool = True
""")

_SAMPLE_PY_UTILS = textwrap.dedent("""\
    # sample_project/utils.py
    def greet(name: str) -> str:
        return f"Hello, {name}!"
""")


def _make_streaming_mock(text: str):
    """Return mock litellm chunks that stream word by word."""
    words = text.split(" ")
    chunks = []
    for word in words:
        c = MagicMock()
        c.choices[0].delta.content = word + " "
        chunks.append(c)
    final = MagicMock()
    final.choices[0].delta.content = None
    chunks.append(final)
    return chunks


def _mock_completion(*args, **kwargs):
    """Universal mock: routes by message content, respects stream kwarg."""
    is_stream = kwargs.get("stream", False)
    messages = kwargs.get("messages", [])

    user_content = ""
    for m in reversed(messages):
        if m.get("role") == "user":
            user_content = m.get("content", "").lower()
            break

    if "auth" in user_content or "oauth" in user_content or "jwt" in user_content:
        text = "The auth-service uses OAuth2 and JWT tokens. Rate limit is 100 req/s."
    elif "payment" in user_content or "stripe" in user_content:
        text = "Payments go through Stripe. PostgreSQL stores transaction records."
    elif "sample" in user_content or "greet" in user_content or "fastapi" in user_content:
        text = "This is the sample project. It uses FastAPI with three modules: main, models, utils."
    elif "plan" in user_content:
        text = json.dumps({
            "summary": "Plan touches auth-service and payments-service.",
            "affected_projects": ["auth-service", "payments-service"],
            "dependencies": [
                {"project": "auth-service", "relation": "OAuth2 tokens", "notes": "rate limit concern"}
            ],
            "risks": [
                {"severity": "high", "title": "Rate limit", "detail": "100 req/s cap", "source": "auth-service"}
            ],
            "prior_art": [],
            "recommended_actions": ["Run memoria ask --project auth-service"],
        })
    else:
        text = "This project uses Python and FastAPI. See the Memory Bank for full details."

    if is_stream:
        return _make_streaming_mock(text)
    else:
        mock = MagicMock()
        mock.choices[0].message.content = text
        return mock


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="session")
def books_dir(tmp_path_factory) -> Path:
    """Temp books directory with 2 pre-seeded Memory Banks."""
    bd = tmp_path_factory.mktemp("e2e_books")
    (bd / "auth_service_memory_bank.md").write_text(_MOCK_BOOK_AUTH, encoding="utf-8")
    (bd / "payments_service_memory_bank.md").write_text(_MOCK_BOOK_PAYMENTS, encoding="utf-8")
    return bd


@pytest.fixture(scope="session")
def sample_project_dir(tmp_path_factory) -> Path:
    """Tiny Python project used for analyze-flow tests."""
    proj = tmp_path_factory.mktemp("sample_project")
    (proj / "main.py").write_text(_SAMPLE_PY_MAIN, encoding="utf-8")
    (proj / "models.py").write_text(_SAMPLE_PY_MODELS, encoding="utf-8")
    (proj / "utils.py").write_text(_SAMPLE_PY_UTILS, encoding="utf-8")
    return proj


@pytest.fixture(scope="session")
def config_file(tmp_path_factory) -> Path:
    """Minimal config.yaml pointing to a harmless model."""
    cfg = tmp_path_factory.mktemp("e2e_config") / "config.yaml"
    cfg.write_text(
        "model: gpt-4o-mini\n"
        "max_tokens: 512\n",
        encoding="utf-8",
    )
    return cfg


@dataclass
class ServerInfo:
    base_url: str
    books_dir: Path


@pytest.fixture(scope="session")
def live_server(books_dir, config_file) -> Generator[ServerInfo, None, None]:
    """
    Start a real uvicorn server for the duration of the E2E test session.
    Yields a ServerInfo(base_url, books_dir).
    """
    import socket
    import uvicorn

    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        port = s.getsockname()[1]

    from memoria.ui import create_app
    app = create_app(
        config_path=str(config_file),
        books_dir=str(books_dir),
    )

    server = uvicorn.Server(uvicorn.Config(
        app=app,
        host="127.0.0.1",
        port=port,
        log_level="error",
    ))

    thread = threading.Thread(target=server.run, daemon=True)

    with patch("litellm.completion", side_effect=_mock_completion):
        thread.start()
        base_url = f"http://127.0.0.1:{port}"
        for _ in range(30):
            try:
                import urllib.request
                urllib.request.urlopen(f"{base_url}/api/projects", timeout=1)
                break
            except Exception:
                time.sleep(0.2)
        else:
            pytest.fail("E2E test server did not start within 6 seconds")

        yield ServerInfo(base_url=base_url, books_dir=books_dir)

        server.should_exit = True
        thread.join(timeout=5)


@pytest.fixture
def http_client(live_server) -> httpx.AsyncClient:
    """Async HTTP client pointed at the live server (test-scoped)."""
    return httpx.AsyncClient(base_url=live_server.base_url, timeout=30.0)


# ── SSE helpers ────────────────────────────────────────────────────────────────

def parse_sse_events(raw: str) -> list[dict]:
    """
    Parse raw SSE text into a list of decoded JSON objects.

    Handles both formats:
      • data: {"type": "done", ...}           — type is in the JSON payload
      • event: done\\ndata: {"message": "..."}  — type is in the SSE event field

    In the second format the event name is injected as {"type": <event_name>}
    into the returned dict so callers can uniformly check e.get("type").

    Input  : "data: {...}\\n\\ndata: {...}\\n\\n"
    Output : [{...}, {...}]
    """
    events = []
    for block in raw.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        event_name: str | None = None
        data_payload: str | None = None
        for line in block.splitlines():
            if line.startswith("event:"):
                event_name = line[len("event:"):].strip()
            elif line.startswith("data:"):
                data_payload = line[len("data:"):].strip()
        if data_payload:
            try:
                obj = json.loads(data_payload)
                # If the SSE `event:` field was set and the payload has no `type`
                # key, inject the event name so tests can check e.get("type").
                if event_name and "type" not in obj:
                    obj["type"] = event_name
                events.append(obj)
            except json.JSONDecodeError:
                pass
    return events
