"""
Book Generator — takes crawled repo data and produces a Memory Bank.
Handles large repos by processing in chunks, then synthesizing.
"""

import time
import json
from pathlib import Path
from datetime import datetime
from typing import Optional
from rich.console import Console

from .models import ModelProvider
from .crawler import RepoCrawler

console = Console()

SYSTEM_PROMPT = """You are the most experienced engineer on this team — you have read every file,
made architectural decisions, debugged the hardest bugs, and onboarded every new hire.

Your job: write a Memory Bank that is THE definitive guide to this project.
Someone reading it should feel like they sat next to you for a week.

Rules:
- Be brutally specific. Name actual files, functions, classes, config keys.
- Explain the WHY behind decisions, not just the WHAT.
- Surface the non-obvious — the traps, the shortcuts, the things that look wrong but aren't.
- If something is unclear from the code, say so honestly. Never invent facts.
- Write for two audiences simultaneously: a new engineer on day 1, and an AI assistant about to edit code.
- The best Memory Bank is one where a reader says "I finally understand this."
"""

BOOK_PROMPT_TEMPLATE = """Analyze this codebase carefully and write a comprehensive Memory Bank.

PROJECT: {project_name}
CONTEXT: {company_context}

DIRECTORY STRUCTURE:
{structure}

FILES:
{files_content}

Write the Memory Bank using EXACTLY this structure. Be thorough — depth matters here:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullet points. Someone who reads nothing else reads this.
 What it does, what tech it uses, the one thing that makes it unique.]

---

## 1. What This Project Does
[The full picture. What problem does it solve? Who uses it and how?
 What does a successful outcome look like for a user of this project?]

## 2. Architecture — How It Works
[Walk through the system end to end. How does data flow? What calls what?
 Draw it in ASCII if it helps. Name the layers and explain why they exist.]

## 3. File & Module Map
[Every important file or directory — one crisp line each.
 Format: `path/to/file.py` — what it does and why it matters]

## 4. Key Concepts & Data Models
[The core abstractions. What are the main objects/schemas/types?
 How do they relate to each other? What would break if you misunderstood one?]

## 5. How to Run This Locally
[Exact steps. Not "install dependencies" — give the actual commands.
 Include environment variables needed, common setup errors, and how to verify it works.]

## 6. Common Workflows
[The 3-5 things a developer does most often in this project.
 Example: "To add a new API endpoint, you..." — walk through it step by step.]

## 7. Non-Obvious Decisions & Gotchas
[This section is gold. What would trip up someone smart?
 Why does X look wrong but isn't? What did you learn the hard way?
 Include: naming conventions, hidden dependencies, config quirks, performance traps.]

## 8. What's Broken / Missing / Next
[Honest assessment. Known bugs, tech debt, missing features.
 What's the next thing that needs to be built or fixed?]

---
"""

# ── Content-type detection ────────────────────────────────────────────────────

CODE_EXTENSIONS = {
    ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".java", ".rb", ".rs",
    ".cpp", ".c", ".cs", ".php", ".swift", ".kt", ".scala", ".sh", ".bash",
    ".sql", ".html", ".css", ".scss", ".vue", ".svelte",
}
AUDIO_EXTENSIONS  = {".mp3", ".m4a", ".wav"}
VIDEO_EXTENSIONS  = {".mp4", ".mov", ".avi", ".mkv", ".webm"}
IMAGE_EXTENSIONS  = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"}
DOC_EXTENSIONS    = {".pdf", ".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls", ".csv"}
NOTEBOOK_EXTENSIONS = {".ipynb"}
WEB_EXTENSIONS    = {".html", ".htm"}

# Filename stems (lowercased, dashes/underscores stripped) that suggest a process/SOP doc
PROCESS_FILENAME_KEYWORDS = {
    "sop", "runbook", "procedure", "procedures", "workflow", "workflows",
    "playbook", "playbooks", "checklist", "checklists", "policy", "policies",
    "escalation", "process", "processes", "protocol", "protocols", "standard",
    "howto", "how-to", "guide", "guidelines", "onboarding", "offboarding",
    "incident", "oncall", "on-call", "deployment", "rollback", "release",
    "triage", "response", "postmortem", "post-mortem", "runsheet",
}


def _detect_content_type(files: dict) -> str:
    """
    Classify a file collection as: 'code', 'audio', 'video', 'document',
    'notebook', 'process', or 'mixed'.
    Used to pick the right generation prompt and progress messages.
    """
    exts = {Path(p).suffix.lower() for p in files}
    has_code     = bool(exts & CODE_EXTENSIONS)
    has_audio    = bool(exts & AUDIO_EXTENSIONS)
    has_video    = bool(exts & VIDEO_EXTENSIONS)
    has_docs     = bool(exts & (DOC_EXTENSIONS | IMAGE_EXTENSIONS | WEB_EXTENSIONS))
    has_notebook = bool(exts & NOTEBOOK_EXTENSIONS)
    has_text     = bool(exts & {".md", ".txt", ".rst"})

    # Single video file (audio + visual frames)
    if has_video and len(files) == 1:
        return "video"
    # Single audio file
    if has_audio and len(files) == 1:
        return "audio"
    # Single image
    if (exts & IMAGE_EXTENSIONS) and len(files) == 1:
        return "image"
    # Notebooks (possibly with some docs)
    if has_notebook and not has_code:
        return "notebook"
    # Process / SOP detection — filename heuristics (before general document check)
    # Applies when there's no code and content is docs/markdown/text
    if not has_code and (has_docs or has_text):
        for fpath in files:
            stem = Path(fpath).stem.lower().replace("-", " ").replace("_", " ")
            words = set(stem.split())
            if words & PROCESS_FILENAME_KEYWORDS:
                return "process"
        # Also scan first ~500 chars of each file for strong process signals
        _process_signals = {
            "step 1", "step 2", "step one", "trigger:", "escalate to",
            "decision point", "prerequisites:", "runbook", "playbook",
            "standard operating procedure", "sop:", "procedure:", "workflow:",
        }
        for _fdata in files.values():
            # _fdata may be a dict {"content": "..."} or a plain string
            _raw = _fdata.get("content", "") if isinstance(_fdata, dict) else _fdata
            _snippet = str(_raw)[:500].lower()
            if any(sig in _snippet for sig in _process_signals):
                return "process"
    # Document collection with no code
    if has_docs and not has_code:
        return "document"
    # Plain-text / markdown collection (no code, no office docs) — treat as document
    if has_text and not has_code and not has_docs:
        return "document"
    # Default: treat as code / mixed
    return "code"


# ── Prompt templates ──────────────────────────────────────────────────────────

# Used when content is audio transcripts
AUDIO_SYSTEM_PROMPT = """You are an expert analyst who turns raw transcripts into
structured, searchable knowledge. Your job is to read a transcript and write a
Memory Bank — a clean, organised reference that captures everything important.

Rules:
- Quote the speaker's actual words when it adds value
- Identify topics, decisions, action items, and open questions
- Do NOT invent anything not present in the transcript
- If the audio is unclear or content is minimal, say so honestly
- Write for someone who wasn't in the room and needs to catch up fast
"""

AUDIO_PROMPT_TEMPLATE = """Here is a transcript from an audio/video recording.
Write a Memory Bank that captures everything important from it.

NAME: {project_name}
CONTEXT: {company_context}

TRANSCRIPT:
{files_content}

Write the Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullets. What was this recording about? Key outcome in one line.]

---

## 1. What This Recording Is About
[Who is speaking? What is the purpose of this recording?
 Meeting, interview, lecture, voice note, call — what type and why it happened.]

## 2. Key Topics Discussed
[Each major topic covered. One subsection per topic with the main points.]

## 3. Decisions Made
[Any explicit decisions, conclusions, or agreements reached.
 If none, write "No explicit decisions recorded."]

## 4. Action Items & Next Steps
[Concrete things someone said they would do, or that need to happen.
 Format: - [ ] Action — Owner (if mentioned)
 If none, write "No action items recorded."]

## 5. Key Quotes & Insights
[The most important or insightful things said verbatim.
 Things worth remembering exactly as spoken.]

## 6. Open Questions
[Things that were raised but not resolved. Unknowns that remain open.]

## 7. Full Transcript
[Include the complete transcript here, timestamped if available.]

---
"""

# Used when content is documents / PDFs / presentations
DOCUMENT_SYSTEM_PROMPT = """You are an expert analyst who turns documents into
structured, searchable knowledge. Your job is to read the document content and
write a Memory Bank — a clean reference that captures everything important.

Rules:
- Be specific — reference actual section names, data points, and figures
- Preserve important numbers, dates, and names exactly
- Do NOT invent anything not in the document
- Write for someone who needs to know what's in this document without reading it
"""

DOCUMENT_PROMPT_TEMPLATE = """Here is the content of a document or document collection.
Write a Memory Bank that captures everything important from it.

NAME: {project_name}
CONTEXT: {company_context}

CONTENT:
{files_content}

Write the Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullets. What is this document about? Who is the audience? Key takeaway.]

---

## 1. What This Document Is About
[Purpose, audience, and scope. Why does this document exist?]

## 2. Key Topics & Sections
[Walk through each major section or topic. What does each cover?]

## 3. Important Data & Facts
[Specific numbers, statistics, dates, names, findings — anything concrete.
 Things that would be useful to look up quickly.]

## 4. Conclusions & Recommendations
[What does the document conclude or recommend?
 If it's a report: findings. If it's a spec: requirements. If it's a plan: outcomes.]

## 5. Open Questions & Gaps
[Things the document raises but doesn't answer.
 Missing information, assumptions made, things flagged for follow-up.]

## 6. Quick Reference
[A bullet-point index of the most important facts for fast retrieval.
 Dates, names, numbers, decisions — the things someone searches for most.]

---
"""

# Used for Jupyter notebooks
NOTEBOOK_SYSTEM_PROMPT = """You are a senior data scientist reviewing a Jupyter notebook.
Write a Memory Bank that explains what the analysis does, the findings, and how to reuse it.
"""

NOTEBOOK_PROMPT_TEMPLATE = """Here is the content of a Jupyter notebook.
Write a Memory Bank that captures the analysis and findings.

NAME: {project_name}
CONTEXT: {company_context}

NOTEBOOK CONTENT:
{files_content}

Write the Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullets. What question does this notebook answer? What was found?]

---

## 1. Purpose & Question
[What problem or question is this notebook trying to answer?]

## 2. Data Sources
[What data is used? Where does it come from? What does it contain?]

## 3. Methodology
[What analysis steps are taken? Walk through the approach.]

## 4. Key Findings
[What were the results? Include actual numbers and charts described.]

## 5. How to Re-run This
[Steps to reproduce the analysis. Dependencies, data paths, environment.]

## 6. Gotchas & Notes
[Anything non-obvious. Data caveats, known issues, assumptions made.]

---
"""


CHUNK_SUMMARY_PROMPT = """Summarize the following files from a codebase.
Be concise. Focus on: what each file does, key functions/classes, important patterns.

FILES:
{files_content}

Return a structured summary that can be used to write documentation."""

DOCUMENT_CHUNK_SUMMARY_PROMPT = """Summarize the following document content.
Be concise but thorough. Extract: key topics, important facts/data, decisions, conclusions.
Preserve specific numbers, names, and dates exactly.

CONTENT:
{files_content}

Return a structured summary capturing all important information."""

DOCUMENT_SYNTHESIS_PROMPT = """You are writing the final Memory Bank for a document collection.
You processed the documents in chunks. Below are the chunk summaries — synthesize them into one
comprehensive Memory Bank. Do not just concatenate — find themes, connect ideas, surface insights.

NAME: {project_name}
CONTEXT: {company_context}

CHUNK SUMMARIES:
{summaries}

Write the Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullets. What is this collection about? Key takeaway.]

---

## 1. What This Collection Is About
[Purpose, audience, and scope.]

## 2. Key Topics & Sections
[Walk through each major topic across all documents.]

## 3. Important Data & Facts
[Specific numbers, statistics, dates, names — anything concrete and worth looking up.]

## 4. Conclusions & Recommendations
[What do these documents conclude, recommend, or decide?]

## 5. Open Questions & Gaps
[Things raised but not answered. Missing information. Assumptions made.]

## 6. Quick Reference
[Bullet-point index of the most searchable facts: dates, names, decisions, numbers.]

---
"""


# ── Process / SOP prompts ─────────────────────────────────────────────────────

PROCESS_SYSTEM_PROMPT = """You are an expert business process analyst and knowledge engineer.
Your job is to read any form of process documentation — SOPs, runbooks, wikis, tickets, meeting
transcripts, incident reports, or informal notes — and distill it into a structured Process
Memory Bank.

Rules:
- Extract the actual steps, not just what the document says about them
- Identify every decision point and branch (if X then Y, else Z)
- Note who owns each step, the escalation path, and what tools are needed
- Flag steps that are unclear, undocumented, or likely outdated
- Confidence reflects how well-documented and tested each step is — be honest
- If the same process appears in multiple documents, reconcile conflicts and note them
- Write for both a human running this for the first time AND an AI agent following instructions
"""

PROCESS_PROMPT_TEMPLATE = """Here is documentation describing a process, procedure, or workflow.
Extract and structure it into a Process Memory Bank.

NAME: {project_name}
CONTEXT: {company_context}

SOURCE CONTENT:
{files_content}

Write the Process Memory Bank using EXACTLY this structure:

# {project_name} — Process Memory Bank
> Last updated: {date} | Generated by Memoria ({model}) | Type: process

---

## TL;DR
[3-5 bullets. What does this process do? Who runs it? When does it trigger? Key outcome.]

---

## Process Overview

| Field | Value |
|-------|-------|
| **Process Name** | [Formal name] |
| **Owner / DRI** | [Person or team responsible] |
| **Trigger** | [What starts this process?] |
| **Scope** | [What is covered? What is excluded?] |
| **Frequency** | [On-demand / daily / weekly / event-driven?] |
| **Estimated Duration** | [How long end-to-end?] |
| **Last Verified** | [When was this last confirmed accurate? Write "Unknown" if not stated.] |
| **Confidence** | [High / Medium / Low — how complete and tested is this documentation?] |

---

## Step-by-Step Procedure

[Number every step. For each step include: what to do, who does it, what tool is used,
the expected output when done, and any warnings or common mistakes.]

### Step 1: [Name]
**Who:** [Role or person]
**Tool:** [System or tool used]
**Action:** [Exactly what to do]
**Output:** [What should be true when this step is complete]
⚠️ **Watch out:** [Common mistake or edge case — omit if none]

[Continue for each step...]

---

## Decision Points & Branching Logic

[A decision point is any "if this, then that" moment in the process.]

| Decision | Condition | If True → | If False → |
|----------|-----------|-----------|------------|
| [Decision name] | [Condition being evaluated] | [Path A] | [Path B] |

---

## Exceptions & Edge Cases

[Specific scenarios that don't follow the standard path.]

| Scenario | What to do differently |
|----------|------------------------|
| [Edge case] | [Modified steps or escalation] |

---

## Escalation Paths

[Who to contact when something goes wrong or falls outside the normal scope.]

| Situation | Escalate To | How | SLA |
|-----------|-------------|-----|-----|
| [Trigger] | [Contact / team] | [Slack / email / PagerDuty / phone] | [Expected response time] |

---

## Tools & Resources Required

- **Systems:** [List all tools and platforms used in this process]
- **Access needed:** [Permissions, credentials, accounts required]
- **Templates / docs:** [Links or locations of reference materials]
- **Dependencies:** [Other processes or teams that must act first]

---

## Confidence & Verification Status

| Section | Confidence | Last Verified | Source |
|---------|------------|---------------|--------|
| [Step group or section] | High / Medium / Low | [Date or "Unknown"] | [Document / Person / Live test] |

**Overall confidence:** [High / Medium / Low]
**Gaps:** [What is missing, assumed, or needs SME review]

---

## Known Issues & Improvement Notes

[Things that are wrong, unclear, outdated, or could be better.]

- [Issue and suggested fix or owner]

---
"""

PROCESS_CHUNK_SUMMARY_PROMPT = """Summarize the following process documentation excerpt.
Extract and preserve: numbered steps, decision points (if/then/else), tools and systems mentioned,
roles and owners, exceptions and edge cases, escalation paths, prerequisites, and any warnings.

CONTENT:
{files_content}

Return a structured summary with all steps numbered, all decisions captured, all tools named."""

PROCESS_SYNTHESIS_PROMPT = """You are writing the final Process Memory Bank.
You processed the source documentation in chunks. Below are the chunk summaries — synthesize them
into one complete, structured Process Memory Bank. Reconcile any conflicts, de-duplicate steps,
and put steps in the correct sequence.

NAME: {project_name}
CONTEXT: {company_context}

CHUNK SUMMARIES:
{summaries}

Write the Process Memory Bank using EXACTLY this structure:

# {project_name} — Process Memory Bank
> Last updated: {date} | Generated by Memoria ({model}) | Type: process

---

## TL;DR
[3-5 bullets. What does this process do? Who runs it? When does it trigger?]

---

## Process Overview

| Field | Value |
|-------|-------|
| **Process Name** | [Formal name] |
| **Owner / DRI** | [Person or team responsible] |
| **Trigger** | [What starts this process?] |
| **Scope** | [What is covered? What is excluded?] |
| **Frequency** | [How often?] |
| **Estimated Duration** | [How long end-to-end?] |
| **Last Verified** | [When last confirmed accurate?] |
| **Confidence** | [High / Medium / Low] |

---

## Step-by-Step Procedure

[Synthesize all steps from all chunks into the correct ordered sequence.]

---

## Decision Points & Branching Logic

| Decision | Condition | If True → | If False → |
|----------|-----------|-----------|------------|

---

## Exceptions & Edge Cases

| Scenario | What to do differently |
|----------|------------------------|

---

## Escalation Paths

| Situation | Escalate To | How | SLA |
|-----------|-------------|-----|-----|

---

## Tools & Resources Required

---

## Confidence & Verification Status

| Section | Confidence | Last Verified | Source |
|---------|------------|---------------|--------|

**Overall confidence:** [High / Medium / Low]
**Gaps:** [What is missing or needs SME review]

---

## Known Issues & Improvement Notes

---
"""

# ─────────────────────────────────────────────────────────────────────────────

SYNTHESIS_PROMPT = """You are writing the final Memory Bank for a project.
You processed the codebase in chunks. Below are the chunk summaries — synthesize them into one
authoritative, comprehensive Memory Bank. Do not just concatenate — think, connect, and write.

PROJECT: {project_name}
CONTEXT: {company_context}
STRUCTURE:
{structure}

CHUNK SUMMARIES:
{summaries}

Write the Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[3-5 bullet points. Someone who reads nothing else reads this.
 What it does, what tech it uses, the one thing that makes it unique.]

---

## 1. What This Project Does
[The full picture. What problem does it solve? Who uses it and how?]

## 2. Architecture — How It Works
[Walk through the system end to end. How does data flow? What calls what?
 Name the layers and explain why they exist.]

## 3. File & Module Map
[Every important file — one crisp line each.
 Format: `path/to/file.py` — what it does and why it matters]

## 4. Key Concepts & Data Models
[Core abstractions, schemas, types. How do they relate? What would break if misunderstood?]

## 5. How to Run This Locally
[Exact commands. Environment variables. Common setup errors. How to verify it works.]

## 6. Common Workflows
[The 3-5 things a developer does most often. Walk through each step by step.]

## 7. Non-Obvious Decisions & Gotchas
[The traps, the shortcuts, the things that look wrong but aren't.
 Naming conventions, hidden dependencies, config quirks, performance traps.]

## 8. What's Broken / Missing / Next
[Known bugs, tech debt, missing features. What needs to be built or fixed next?]

---
"""

SUB_UNIT_SYSTEM_PROMPT = """You are the most experienced engineer on this team — you have read every
file in this module, written half of it, and debugged every edge case.

Your job: write a focused Memory Bank for ONE module/sub-package of a larger project.
A developer reading this should be able to work confidently in this module without
reading the rest of the codebase first.

Rules:
- Be specific to THIS module — not the whole project.
- Name actual files, functions, classes, and exported symbols.
- Explain what this module's public interface IS and what callers should/shouldn't rely on.
- Note connections to sibling modules (what calls this, what this calls).
- Surface the non-obvious — gotchas, conventions, why things are structured the way they are.
- Never invent facts. If something is unclear from the code, say so.
"""

SUB_UNIT_PROMPT_TEMPLATE = """Analyse this module carefully and write a focused Memory Bank for it.

PROJECT: {project_name}
MODULE PATH: {unit_name}
MODULE TYPE: {unit_type}
PROJECT CONTEXT: {company_context}

DIRECTORY STRUCTURE:
{structure}

FILES IN THIS MODULE:
{files_content}

Write the Memory Bank using EXACTLY this structure:

# {unit_name} — Memory Bank
> Module of {project_name} | Last updated: {date} | Generated by Memoria ({model})

---

## TL;DR
[2-3 bullet points. What does this module do? Who uses it? What's its single responsibility?]

---

## 1. What This Module Does
[The specific job of this module within the larger project.
 What problem does it solve? What would break if this module didn't exist?]

## 2. Public Interface
[Every public function, class, or export — one crisp line each.
 Format: `function_name(params)` — what it does, what it returns, when to use it.
 Include: what callers must know, what NOT to rely on (internal details).]

## 3. File Map
[Every file in this module — one line each.
 Format: `filename.py` — what it contains and why it exists separately.]

## 4. Key Patterns & Conventions
[How is this module structured internally? Any naming conventions, base classes,
 error handling patterns, or data flow patterns callers need to know?]

## 5. Connections to Other Modules
[What does this module import from the rest of the project?
 What modules import from this one? Any circular dependency risks?]

## 6. Gotchas & Non-Obvious Behaviour
[Things that would trip up someone smart. Side effects, order dependencies,
 config requirements, things that look wrong but aren't.]

---
"""

ROOT_SUMMARY_SYSTEM_PROMPT = """You are writing the root-level Memory Bank for a project that has
been split into sub-units. You have a summary of each sub-unit already written.

Your job: synthesize the sub-unit summaries into a high-level Memory Bank that:
- Explains the project as a whole (purpose, architecture, tech stack)
- Shows how the sub-units relate to each other (the spider-web view)
- Guides a new engineer to the right sub-unit for any given task
- Surfaces project-wide patterns and conventions that cut across modules

Do NOT repeat content that is better covered in the sub-unit Memory Banks.
Focus on the connective tissue — the architecture, the data flows, the big picture.
"""

ROOT_SUMMARY_PROMPT_TEMPLATE = """You are writing the root-level Memory Bank for {project_name}.
The project has been analysed as {unit_count} sub-units. Here are their Memory Banks:

PROJECT: {project_name}
CONTEXT: {company_context}

ROOT-LEVEL FILES (not covered by any sub-unit):
{root_files_content}

SUB-UNIT MEMORY BANKS:
{sub_unit_summaries}

Write the root Memory Bank using EXACTLY this structure:

# {project_name} — Memory Bank
> Last updated: {date} | Generated by Memoria ({model}) | {unit_count} sub-units

---

## TL;DR
[3-5 bullet points. Someone who reads nothing else reads this.
 What it does, what tech it uses, the one thing that makes it unique.]

---

## 1. What This Project Does
[The full picture. Problem solved, who uses it, what success looks like.]

## 2. Architecture — Sub-Unit Map
[How the sub-units relate. What calls what. Data flow across modules.
 Draw it in ASCII if it helps. One line per sub-unit: path — role in the system.]

## 3. Root-Level Files
[Files that live at the project root and don't belong to any sub-unit.
 Format: `filename.py` — what it does and why it's at the root level.]

## 4. Cross-Cutting Patterns
[Conventions, abstractions, or patterns that appear across multiple sub-units.
 Error handling strategy, config loading, auth model, logging approach, etc.]

## 5. How to Run This Locally
[Exact commands. Environment variables. Common setup errors. How to verify it works.]

## 6. Where to Start for Common Tasks
[Guide a developer to the right sub-unit:
 "To change X, start in sub-unit Y because..." — 5-8 common tasks.]

## 7. Known Issues & What's Next
[Honest assessment of tech debt, missing features, things actively being built.]

---
"""


class BookGenerator:
    """
    Generates a Memory Bank from crawled repo data.
    Automatically handles large repos by chunking.
    """

    CHUNK_THRESHOLD = 60_000  # chars — above this, we chunk

    def __init__(self, config_path: str = "config.yaml"):
        self.model = ModelProvider(config_path)
        self.config_path = config_path

    def generate(
        self,
        repo_path: str,
        company_context: str,
        output_dir: str = "books",
        on_progress=None,
        content_type_override: Optional[str] = None,
    ) -> str:
        """
        Full pipeline: crawl → generate → save → return output path.
        on_progress: optional callback(step: str) for UI updates.
        """

        def progress(msg):
            if on_progress:
                on_progress(msg)

        # Step 1: Crawl
        # Pick a pre-crawl label based on whether the path looks like a doc folder
        _p = Path(repo_path)
        _pre_label = "Reading files..." if _p.is_dir() and not any(
            (_p / sig).exists() for sig in (
                "package.json", "requirements.txt", "setup.py", "pyproject.toml",
                "Cargo.toml", "go.mod", "Makefile", "Dockerfile", ".git"
            )
        ) else "Crawling repository..."
        progress(_pre_label)
        crawler = RepoCrawler(repo_path, self.config_path)
        data = crawler.crawl()

        project_name = data["name"]
        structure = data["structure"]
        files = data["files"]

        # Detect content type now that we have the file list
        content_type = content_type_override or _detect_content_type(files)
        _action = {
            "audio":    "Transcribing audio",
            "video":    "Analysing video (frames + audio)",
            "image":    "Analysing image",
            "document": "Extracting documents",
            "notebook": "Reading notebook",
            "process":  "Extracting process / SOP",
        }.get(content_type, "Analysing")

        # Step 2: Build file content string
        files_content = self._format_files(files)
        total_chars = len(files_content)

        # Step 3: Generate book (single pass or chunked)
        if total_chars <= self.CHUNK_THRESHOLD:
            progress(f"{_action} ({data['stats']['total_files']} file(s))...")
            book_content = self._generate_single(
                project_name, company_context, structure, files_content, files
            )
        else:
            progress(f"Large collection ({total_chars // 1000}K chars). Processing in chunks...")
            book_content = self._generate_chunked(
                project_name, company_context, structure, crawler, on_progress, files
            )

        # Step 3.5: Inject content type into the metadata header line so the UI
        # can display the correct badge without heuristics.
        import re as _re
        _type_tag = {
            "audio":       "audio",
            "video":       "video",
            "image":       "image",
            "document":    "docs",
            "notebook":    "notebook",
            "mixed":       "mixed",
            "spreadsheet": "sheet",
            "process":     "process",
        }.get(content_type, "code")
        book_content = _re.sub(
            r"(\| Generated by Memoria \([^)]+\))",
            rf"\1 | Type: {_type_tag}",
            book_content,
            count=1,
        )

        # Step 4: Save
        progress("Saving memory bank...")
        output_path = self._save_book(project_name, book_content, output_dir)

        # Record metadata so Update from UI knows the source path
        try:
            from .meta import record as _meta_record
            _meta_record(project_name, repo_path, company_context)
        except Exception:
            pass  # metadata recording is best-effort, never block

        return output_path

    def generate_from_text(
        self,
        source_name: str,
        company_context: str,
        content: str,
        output_dir: str = "books",
        on_progress=None,
    ) -> str:
        """
        Generate a Memory Bank from raw text — used by `memoria pull`.
        Bypasses the crawler entirely; content is provided directly (e.g. from an MCP source).
        Automatically chunks large content the same way the crawler-based path does.
        """
        def progress(msg):
            if on_progress:
                on_progress(msg)

        project_name = source_name
        structure = f"[Content pulled from external source: {source_name}]"

        # Treat all MCP-pulled content as a document collection
        # (a synthetic single-file dict so _detect_content_type → 'document')
        files = {f"{source_name}.md": content}

        total_chars = len(content)

        if total_chars <= self.CHUNK_THRESHOLD:
            progress(f"Generating memory bank ({total_chars // 1000}K chars)...")
            book_content = self._generate_single(
                project_name, company_context, structure, content, files
            )
        else:
            # Split into CHUNK_THRESHOLD-sized chunks and summarize each, then synthesize
            progress(f"Large content ({total_chars // 1000}K chars). Processing in chunks...")
            raw_chunks = [
                content[i: i + self.CHUNK_THRESHOLD]
                for i in range(0, total_chars, self.CHUNK_THRESHOLD)
            ]
            summaries: list[str] = []
            consecutive_rl = 0
            for i, chunk in enumerate(raw_chunks):
                progress(f"Processing chunk {i + 1} of {len(raw_chunks)}...")
                for attempt in range(2):  # original + 1 retry
                    try:
                        summary = self.model.complete(
                            DOCUMENT_SYSTEM_PROMPT,
                            DOCUMENT_CHUNK_SUMMARY_PROMPT.format(files_content=chunk),
                        )
                        summaries.append(f"--- Chunk {i + 1} ---\n{summary}")
                        consecutive_rl = 0
                        break
                    except RuntimeError as e:
                        if str(e).startswith("[AUTH]"):
                            raise  # never retry auth failures
                        if "[RATELIMIT]" in str(e) or "[TRANSIENT]" in str(e):
                            consecutive_rl += 1
                            if consecutive_rl >= 3:
                                raise RuntimeError(
                                    "Rate limit hit 3 times in a row. "
                                    "Your API quota may be exhausted. "
                                    "Wait a few minutes, check your quota, or switch model."
                                ) from e
                            wait = 15 * (attempt + 1)
                            progress(
                                f"Rate limit hit ({consecutive_rl}/3). "
                                f"Waiting {wait}s before retry…"
                            )
                            time.sleep(wait)
                            if attempt == 1:
                                raise
                        else:
                            raise
                if i < len(raw_chunks) - 1:
                    time.sleep(2)

            progress("Synthesizing final memory bank...")
            book_content = self._call_with_retry(
                DOCUMENT_SYSTEM_PROMPT,
                DOCUMENT_SYNTHESIS_PROMPT.format(
                    project_name=project_name,
                    company_context=company_context,
                    summaries="\n\n".join(summaries),
                    date=datetime.now().strftime("%Y-%m-%d"),
                    model=self.model.model,
                ),
            )

        # Inject type tag: MCP-pulled content is always treated as 'mcp'
        import re as _re2
        book_content = _re2.sub(
            r"(\| Generated by Memoria \([^)]+\))",
            r"\1 | Type: mcp",
            book_content,
            count=1,
        )

        progress("Saving memory bank...")
        return self._save_book(project_name, book_content, output_dir)

    def _generate_single(
        self, project_name: str, company_context: str, structure: str,
        files_content: str, files: dict = None
    ) -> str:
        """Single model call — picks the right prompt based on content type."""
        content_type = _detect_content_type(files or {})
        date = datetime.now().strftime("%Y-%m-%d")

        template_args = dict(
            project_name=project_name,
            company_context=company_context,
            files_content=files_content,
            date=date,
            model=self.model.model,
        )

        if content_type in ("audio", "video"):
            return self.model.complete(
                AUDIO_SYSTEM_PROMPT,
                AUDIO_PROMPT_TEMPLATE.format(**template_args),
            )
        elif content_type in ("document", "image"):
            return self.model.complete(
                DOCUMENT_SYSTEM_PROMPT,
                DOCUMENT_PROMPT_TEMPLATE.format(**template_args),
            )
        elif content_type == "notebook":
            return self.model.complete(
                NOTEBOOK_SYSTEM_PROMPT,
                NOTEBOOK_PROMPT_TEMPLATE.format(**template_args),
            )
        elif content_type == "process":
            return self.model.complete(
                PROCESS_SYSTEM_PROMPT,
                PROCESS_PROMPT_TEMPLATE.format(**template_args),
            )
        else:
            # Code / mixed — original behaviour
            prompt = BOOK_PROMPT_TEMPLATE.format(
                structure=structure, **template_args
            )
            return self.model.complete(SYSTEM_PROMPT, prompt)

    def _generate_chunked(
        self, project_name: str, company_context: str, structure: str,
        crawler: RepoCrawler, on_progress=None, files: dict = None
    ) -> str:
        """Multi-pass generation for large repos/collections — prompts adapt to content type."""
        content_type = _detect_content_type(files or {})
        is_doc     = content_type in ("document", "audio", "video", "notebook", "image")
        is_process = content_type == "process"

        if is_process:
            chunk_system   = PROCESS_SYSTEM_PROMPT
            chunk_prompt   = PROCESS_CHUNK_SUMMARY_PROMPT
            synth_system   = PROCESS_SYSTEM_PROMPT
            synth_template = PROCESS_SYNTHESIS_PROMPT
        elif is_doc:
            chunk_system   = DOCUMENT_SYSTEM_PROMPT
            chunk_prompt   = DOCUMENT_CHUNK_SUMMARY_PROMPT
            synth_system   = DOCUMENT_SYSTEM_PROMPT
            synth_template = DOCUMENT_SYNTHESIS_PROMPT
        else:
            chunk_system   = SYSTEM_PROMPT
            chunk_prompt   = CHUNK_SUMMARY_PROMPT
            synth_system   = SYSTEM_PROMPT
            synth_template = SYNTHESIS_PROMPT

        chunks = crawler.get_chunked_files()
        summaries = []
        consecutive_rl = 0  # consecutive rate-limit failures across chunks

        for i, chunk in enumerate(chunks):
            if on_progress:
                on_progress(f"Processing chunk {i + 1} of {len(chunks)}...")

            files_content = self._format_files(chunk)

            for attempt in range(2):  # max 2 attempts: original + 1 retry
                try:
                    summary = self.model.complete(
                        chunk_system,
                        chunk_prompt.format(files_content=files_content),
                    )
                    summaries.append(f"--- Chunk {i + 1} ---\n{summary}")
                    consecutive_rl = 0  # reset on success
                    break
                except RuntimeError as e:
                    if "429" in str(e) or "rate" in str(e).lower() or "quota" in str(e).lower():
                        consecutive_rl += 1
                        if consecutive_rl >= 3:
                            raise RuntimeError(
                                "Rate limit hit 3 times in a row. "
                                "Your API quota may be exhausted. "
                                "Wait a few minutes, check your quota, or switch model."
                            ) from e
                        wait = 15 * (attempt + 1)   # 15s then 30s
                        if on_progress:
                            on_progress(
                                f"Rate limit hit ({consecutive_rl}/3). "
                                f"Waiting {wait}s before retry…"
                            )
                        time.sleep(wait)
                        if attempt == 1:
                            raise
                    else:
                        raise

            if i < len(chunks) - 1:
                time.sleep(2)

        if on_progress:
            on_progress("Synthesizing final memory bank...")

        synthesis_prompt = synth_template.format(
            project_name=project_name,
            company_context=company_context,
            structure=structure,
            summaries="\n\n".join(summaries),
            date=datetime.now().strftime("%Y-%m-%d"),
            model=self.model.model,
        )
        for attempt in range(2):  # max 2 attempts: original + 1 retry
            try:
                return self.model.complete(synth_system, synthesis_prompt)
            except RuntimeError as e:
                err = str(e)
                if any(x in err for x in ["503", "502", "unavailable", "connection", "disconnected"]):
                    wait = 15 * (attempt + 1)
                    if on_progress:
                        on_progress(f"Model temporarily unavailable. Retrying in {wait}s…")
                    time.sleep(wait)
                    if attempt == 1:
                        raise
                else:
                    raise

    def _format_files(self, files: dict) -> str:
        """Format file dict into a readable string for the model."""
        parts = []
        for path, data in files.items():
            parts.append(f"### {path}\n```\n{data['content']}\n```")
        return "\n\n".join(parts)

    def _save_book(self, project_name: str, content: str, output_dir: str) -> str:
        """
        Save the generated book — one file per project.

        Behaviour:
        - One canonical file: {project}_memory_bank.md
        - Before overwriting, the previous version moves to .archive/
        - Archive files older than ARCHIVE_TTL_DAYS are auto-purged (recycle bin)
        """
        ARCHIVE_TTL_DAYS = 30

        books_path = Path(output_dir)
        books_path.mkdir(parents=True, exist_ok=True)

        archive_path = books_path / ".archive"
        archive_path.mkdir(exist_ok=True)

        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        book_file = books_path / f"{safe_name}_memory_bank.md"

        # ── Archive previous version before overwriting ──
        if book_file.exists():
            prev_modified = datetime.fromtimestamp(book_file.stat().st_mtime)
            archive_name = f"{safe_name}_{prev_modified.strftime('%Y%m%d_%H%M%S')}.md"
            archive_target = archive_path / archive_name
            # Handle sub-second collisions (e.g. rapid saves in tests or loops)
            counter = 1
            while archive_target.exists():
                archive_target = archive_path / (
                    f"{safe_name}_{prev_modified.strftime('%Y%m%d_%H%M%S')}_{counter}.md"
                )
                counter += 1
            book_file.rename(archive_target)

        # ── Enforce correct header (AI sometimes overwrites it) ──
        content = self._enforce_header(content, project_name)

        # ── Write new book (single file, timestamp inside content) ──
        book_file.write_text(content, encoding="utf-8")

        # ── Auto-index into vector search ──
        try:
            from .search import index_book
            index_book(safe_name, content, output_dir)
        except Exception:
            pass  # Search indexing is best-effort, never block the main flow

        # ── Audit ──
        try:
            from .audit import log_action as _audit
            _audit("generate_book", target=project_name, config_path=self.config_path)
        except Exception:
            pass

        # ── Purge archive files older than TTL (recycle bin behaviour) ──
        self._purge_old_archives(archive_path, ARCHIVE_TTL_DAYS)

        return str(book_file)

    def _purge_old_archives(self, archive_path: Path, ttl_days: int):
        """Delete archive files older than ttl_days. Silent — never blocks the user."""
        try:
            cutoff = datetime.now().timestamp() - (ttl_days * 86400)
            for old_file in archive_path.glob("*.md"):
                if old_file.stat().st_mtime < cutoff:
                    old_file.unlink()
        except Exception:
            pass  # Archive cleanup is best-effort, never crash the main flow

    # ─────────────────────────────────────────────────────────────
    # HIERARCHICAL: per-sub-unit + root-summary generation
    # ─────────────────────────────────────────────────────────────

    def _save_subunit_book(
        self,
        project_name: str,
        unit_name: str,
        content: str,
        output_dir: str,
    ) -> str:
        """
        Save a sub-unit Memory Bank to:
            books/{project_name}/{unit_name}/_mb.md

        unit_name is the relative path from repo root (e.g. "src/auth").
        Uses forward slashes internally; creates parent dirs as needed.
        """
        safe_proj = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        # Normalise separators → forward slash components → safe dir names per segment
        segments = Path(unit_name.replace("\\", "/")).parts
        safe_segments = [
            "".join(c if c.isalnum() or c in "-_." else "_" for c in seg)
            for seg in segments
        ]
        unit_dir = Path(output_dir) / safe_proj / Path(*safe_segments)
        unit_dir.mkdir(parents=True, exist_ok=True)
        mb_path = unit_dir / "_mb.md"
        mb_path.write_text(content, encoding="utf-8")
        return str(mb_path)

    async def generate_subunit(
        self,
        unit,              # SubUnit from core.structure
        project_name: str,
        company_context: str,
        output_dir: str,
        on_progress=None,
    ) -> tuple:
        """
        Async: generate a Memory Bank for one sub-unit.
        Returns (unit_name, mb_path, content).
        Uses async_complete() so multiple sub-units can run via asyncio.gather().
        """
        if on_progress:
            on_progress(f"Analysing {unit.name}…")

        crawler = RepoCrawler(str(unit.path), self.config_path)
        data = crawler.crawl()
        structure = data.get("structure", "")
        files = data.get("files", {})
        files_content = self._format_files(files)

        date = datetime.now().strftime("%Y-%m-%d")
        prompt = SUB_UNIT_PROMPT_TEMPLATE.format(
            project_name=project_name,
            unit_name=unit.name,
            unit_type=unit.type,
            company_context=company_context,
            structure=structure,
            files_content=files_content,
            date=date,
            model=self.model.model,
        )

        content = await self.model.async_complete(SUB_UNIT_SYSTEM_PROMPT, prompt)
        mb_path = self._save_subunit_book(project_name, unit.name, content, output_dir)

        if on_progress:
            on_progress(f"Done: {unit.name}")

        return unit.name, mb_path, content

    async def generate_hierarchical(
        self,
        repo_path: str,
        project_name: str,
        company_context: str,
        output_dir: str = "books",
        on_progress=None,
    ) -> dict:
        """
        Full hierarchical pipeline:
          1. Discover sub-unit boundaries (core.structure)
          2. Generate all sub-unit Memory Banks in parallel (asyncio.gather)
          3. Crawl root-level files (not in any sub-unit)
          4. Synthesise root Memory Bank from sub-unit summaries + root files
          5. Save root Memory Bank to books/{project_name}/{project_name}_memory_bank.md

        Returns:
            {
                "root": str,                    # path to root _memory_bank.md
                "sub_units": {name: path, ...}, # path per sub-unit _mb.md
                "unit_count": int,
            }
        """
        import asyncio as _aio
        from .core.structure import discover_structure, flatten

        def progress(msg):
            if on_progress:
                on_progress(msg)

        # ── Step 1: discover structure ────────────────────────────────────────
        progress("Discovering structure…")
        units = discover_structure(repo_path)
        leaf_units = flatten(units)
        progress(f"Found {len(leaf_units)} sub-units")

        # ── Step 2: generate sub-unit Memory Banks in parallel ────────────────
        progress(f"Generating {len(leaf_units)} sub-unit Memory Banks in parallel…")
        tasks = [
            self.generate_subunit(unit, project_name, company_context, output_dir, on_progress)
            for unit in leaf_units
        ]
        results = await _aio.gather(*tasks, return_exceptions=True)

        sub_unit_map: dict[str, str] = {}   # unit_name → mb_path
        sub_unit_contents: list[str] = []

        for r in results:
            if isinstance(r, Exception):
                progress(f"Warning: sub-unit generation failed: {r}")
                continue
            unit_name, mb_path, content = r
            sub_unit_map[unit_name] = mb_path
            sub_unit_contents.append(f"### Sub-unit: {unit_name}\n\n{content}")

        # ── Step 3: crawl root-level files (skip sub-unit paths) ─────────────
        progress("Analysing root-level files…")
        sub_unit_paths = {str(u.path) for u in leaf_units}
        root_crawler = RepoCrawler(repo_path, self.config_path)
        root_data = root_crawler.crawl()
        root_files = {
            k: v for k, v in root_data.get("files", {}).items()
            if not any(str(Path(repo_path) / k).startswith(p) for p in sub_unit_paths)
        }
        root_files_content = self._format_files(root_files) if root_files else "(none)"

        # ── Step 4: synthesise root Memory Bank ──────────────────────────────
        progress("Synthesising root Memory Bank…")
        date = datetime.now().strftime("%Y-%m-%d")
        root_prompt = ROOT_SUMMARY_PROMPT_TEMPLATE.format(
            project_name=project_name,
            company_context=company_context,
            unit_count=len(leaf_units),
            root_files_content=root_files_content,
            sub_unit_summaries="\n\n---\n\n".join(sub_unit_contents),
            date=date,
            model=self.model.model,
        )
        root_content = await self.model.async_complete(ROOT_SUMMARY_SYSTEM_PROMPT, root_prompt)

        # ── Step 5: save root Memory Bank ────────────────────────────────────
        root_path = self._save_book(project_name, root_content, output_dir)
        progress(f"Done. {len(leaf_units)} sub-units + root Memory Bank saved.")

        return {
            "root": root_path,
            "sub_units": sub_unit_map,
            "unit_count": len(leaf_units),
        }

    # ─────────────────────────────────────────────────────────────
    # SPLIT: 1 team → multiple teams
    # ─────────────────────────────────────────────────────────────

    def propose_split(self, book_content: str, split_description: str) -> str:
        """
        Analyse an existing memory bank and propose ownership zones for a team split.
        Returns a human-readable proposal the user can confirm or adjust before committing.
        """
        prompt = f"""A team that owns this project is splitting. Here is how they described the split:

SPLIT DESCRIPTION:
{split_description}

EXISTING MEMORY BANK:
{book_content}

Analyse the memory bank and propose ownership boundaries. Your response must follow this exact format:

PROPOSED SPLIT:

SHARED (parent book — all teams inherit this):
- List modules, files, or concepts that every team needs to understand
- Explain why each is shared

[REPEAT THIS BLOCK FOR EACH NEW TEAM:]
TEAM: [team name from split description]
OWNS:
- List the specific modules, files, folders, features this team owns
- One line each, be specific
NEEDS FROM SHARED:
- What from the parent book is critical for this team to understand

POTENTIAL CONFLICTS (files/modules owned by more than one team):
- List any files or concepts that span team boundaries
- Propose who "owns" each conflict point

Does this match the intent? Confirm or describe adjustments."""

        return self._call_with_retry(
            SYSTEM_PROMPT,
            prompt,
            "Proposing split boundaries..."
        )

    def save_split_plan(
        self,
        project_name: str,
        book_content: str,
        split_description: str,
        confirmed_proposal: str,
        output_dir: str,
    ) -> str:
        """
        Save a split plan before executing.
        Enables `--undo` to fully restore the original state.
        Returns path to the plan file.
        """
        books_path = Path(output_dir)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        plan = {
            "project_name": project_name,
            "created_at": datetime.now().isoformat(),
            "split_description": split_description,
            "confirmed_proposal": confirmed_proposal,
            "original_book_content": book_content,
            "status": "pending",  # pending → executed → undone
        }
        plan_path = books_path / f"{safe_name}_split_plan.json"
        plan_path.write_text(json.dumps(plan, indent=2), encoding="utf-8")
        return str(plan_path)

    def undo_split(self, project_name: str, output_dir: str, on_progress=None) -> str:
        """
        Undo a previously executed split by restoring the original book
        and archiving all child books created by the split.
        """
        def progress(msg):
            if on_progress:
                on_progress(msg)

        books_path = Path(output_dir)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        plan_path = books_path / f"{safe_name}_split_plan.json"

        if not plan_path.exists():
            raise FileNotFoundError(
                f"No split plan found for '{project_name}'. "
                f"Expected: {plan_path}"
            )

        plan = json.loads(plan_path.read_text(encoding="utf-8"))

        if plan.get("status") == "undone":
            raise RuntimeError("This split has already been undone.")

        # ── Restore original book ──
        progress("Restoring original Memory Bank...")
        original_book = books_path / f"{safe_name}_memory_bank.md"

        # Archive any child books that exist from the split
        archive_path = books_path / ".archive"
        archive_path.mkdir(exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        team_names = self._extract_team_names(plan["confirmed_proposal"])
        for team in team_names:
            safe_team = "".join(c if c.isalnum() or c in "-_" else "_" for c in team)
            child_book = books_path / f"{safe_name}_{safe_team}_memory_bank.md"
            if child_book.exists():
                progress(f"Archiving {child_book.name}...")
                child_book.rename(archive_path / f"{safe_name}_{safe_team}_undone_{ts}.md")

        # Also archive shared parent if it exists
        shared_book = books_path / f"{safe_name}_shared_memory_bank.md"
        if shared_book.exists():
            shared_book.rename(archive_path / f"{safe_name}_shared_undone_{ts}.md")

        # Restore original
        original_book.write_text(plan["original_book_content"], encoding="utf-8")

        # Mark plan as undone
        plan["status"] = "undone"
        plan["undone_at"] = datetime.now().isoformat()
        plan_path.write_text(json.dumps(plan, indent=2), encoding="utf-8")

        progress("Original Memory Bank restored.")
        return str(original_book)

    def execute_split(
        self,
        book_content: str,
        project_name: str,
        split_description: str,
        confirmed_proposal: str,
        output_dir: str,
        on_progress=None,
    ) -> dict:
        """
        Execute a confirmed split. Generates:
        - 1 parent (shared foundation) book
        - N child books (one per team)
        Archives the original book.
        Returns dict of {role: output_path}
        """
        date = datetime.now().strftime("%Y-%m-%d")

        def progress(msg):
            if on_progress:
                on_progress(msg)

        results = {}

        # ── Generate parent (shared) book ──
        progress("Generating shared parent book...")
        parent_prompt = f"""Based on the split below, write the SHARED PARENT Memory Bank.
This book is the foundation — every team reads it first.
Only include what ALL teams need: shared architecture, shared modules, setup, conventions.
Do NOT include team-specific details.

ORIGINAL MEMORY BANK:
{book_content}

CONFIRMED SPLIT:
{confirmed_proposal}

Write a complete Memory Bank for the shared foundation using the standard structure:
# {project_name} — Shared Foundation
> Last updated: {date} | This book is inherited by all team books.

## TL;DR
## 1. What This Project Does
## 2. Architecture — How It All Fits Together
## 3. Shared Modules & Files
## 4. Key Concepts Every Team Must Know
## 5. How to Run Locally
## 6. Conventions & Standards (apply to all teams)
## 7. Known Shared Issues
---"""

        parent_content = self._call_with_retry(SYSTEM_PROMPT, parent_prompt)
        parent_path = self._save_book(f"{project_name}_shared", parent_content, output_dir)
        results["shared"] = parent_path

        # ── Generate child book for each team ──
        teams = self._extract_team_names(confirmed_proposal)
        for team_name in teams:
            progress(f"Generating book for {team_name}...")
            child_prompt = f"""Write the Memory Bank for {team_name} only.
Start by referencing the shared parent book, then go deep on what this team owns.

ORIGINAL MEMORY BANK:
{book_content}

CONFIRMED SPLIT:
{confirmed_proposal}

Write the team-specific Memory Bank:
# {project_name} — {team_name} Team
> Last updated: {date} | Read the Shared Foundation book first, then this one.

## TL;DR (this team's scope)
## 1. What This Team Owns
## 2. Architecture — This Team's Corner
## 3. File & Module Map (team-specific only)
## 4. Key Concepts Specific to This Team
## 5. Common Workflows for This Team
## 6. Interfaces With Other Teams (what you call, what calls you)
## 7. Gotchas & Non-Obvious Decisions
## 8. What's Missing / Next for This Team
---"""
            child_content = self._call_with_retry(SYSTEM_PROMPT, child_prompt)
            safe_team = "".join(c if c.isalnum() or c in "-_" else "_" for c in team_name)
            child_path = self._save_book(f"{project_name}_{safe_team}", child_content, output_dir)
            results[team_name] = child_path
            time.sleep(2)  # avoid rate limits between team books

        # ── Archive the original single book ──
        books_path = Path(output_dir)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        original = books_path / f"{safe_name}_memory_bank.md"
        if original.exists():
            archive_path = books_path / ".archive"
            archive_path.mkdir(exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            original.rename(archive_path / f"{safe_name}_pre_split_{ts}.md")

        # ── Mark split plan as executed ──
        plan_path = books_path / f"{safe_name}_split_plan.json"
        if plan_path.exists():
            plan = json.loads(plan_path.read_text(encoding="utf-8"))
            plan["status"] = "executed"
            plan["executed_at"] = datetime.now().isoformat()
            plan["generated_books"] = list(results.keys())
            plan_path.write_text(json.dumps(plan, indent=2), encoding="utf-8")

        return results

    def _extract_team_names(self, proposal: str) -> list:
        """Parse team names out of the proposal text."""
        import re
        names = re.findall(r"TEAM:\s*(.+)", proposal)
        return [n.strip() for n in names] if names else ["Team_A", "Team_B"]

    # ─────────────────────────────────────────────────────────────
    # MERGE: multiple teams → 1 team
    # ─────────────────────────────────────────────────────────────

    def merge_books(
        self,
        books: list,
        merged_project_name: str,
        merge_context: str,
        output_dir: str,
        on_progress=None,
    ) -> str:
        """
        Merge multiple memory banks into one unified book.
        books = list of (project_name, book_content) tuples.
        Archives all source books.
        Returns path to merged book.
        """
        def progress(msg):
            if on_progress:
                on_progress(msg)

        progress(f"Merging {len(books)} memory banks into one...")

        books_formatted = "\n\n".join(
            f"=== BOOK: {name} ===\n{content}"
            for name, content in books
        )

        date = datetime.now().strftime("%Y-%m-%d")
        prompt = f"""Multiple teams are merging into one. Their individual Memory Banks are below.
Your job: write ONE unified Memory Bank that combines all knowledge without duplication.

REASON FOR MERGE:
{merge_context}

SOURCE BOOKS:
{books_formatted}

Rules:
- Deduplicate — if two books describe the same module, write it once
- Highlight what changed — note in "Architecture" that these teams merged and what that means
- Flag conflicts — if two books contradict each other, surface that in Gotchas
- Be complete — no knowledge from any source book should be lost

Write the unified Memory Bank:
# {merged_project_name} — Memory Bank
> Last updated: {date} | Merged from: {", ".join(n for n, _ in books)}

## TL;DR
## 1. What This Project Does (unified scope)
## 2. Architecture — How It All Works Now
## 3. File & Module Map
## 4. Key Concepts & Data Models
## 5. How to Run Locally
## 6. Common Workflows
## 7. Gotchas & Non-Obvious Decisions (includes pre-merge context)
## 8. What's Missing / Next
---"""

        merged_content = self._call_with_retry(SYSTEM_PROMPT, prompt, "Synthesising unified book...")
        output_path = self._save_book(merged_project_name, merged_content, output_dir)

        # ── Archive all source books ──
        books_path = Path(output_dir)
        archive_path = books_path / ".archive"
        archive_path.mkdir(exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        for name, _ in books:
            safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
            src = books_path / f"{safe}_memory_bank.md"
            if src.exists():
                src.rename(archive_path / f"{safe}_pre_merge_{ts}.md")

        return output_path

    # ─────────────────────────────────────────────────────────────
    # DRAFT + APPROVAL FLOW
    # ─────────────────────────────────────────────────────────────

    def _get_git_changed_files(self, repo_dir: str, since_ts: float) -> set | None:
        """
        Use git to find files changed since `since_ts` (epoch seconds).

        Checks:
          1. Commits landed since that timestamp  (git log --since)
          2. Uncommitted working-tree changes     (git status --porcelain)

        Returns a set of relative paths, or None if the directory is not a git
        repo or git is not installed — caller should fall back to mtime.
        """
        import subprocess
        from datetime import datetime as _dt

        since_iso = _dt.fromtimestamp(since_ts).strftime("%Y-%m-%dT%H:%M:%S")
        changed: set = set()

        try:
            # ── Committed changes since last_analyzed ──────────────────
            r1 = subprocess.run(
                ["git", "log", f"--since={since_iso}", "--name-only", "--pretty=format:"],
                capture_output=True, cwd=repo_dir, timeout=10,
            )
            if r1.returncode != 0:
                return None   # not a git repo

            for line in r1.stdout.decode("utf-8", errors="replace").splitlines():
                f = line.strip()
                if f:
                    changed.add(f.replace("\\", "/"))

            # ── Uncommitted modifications / additions ───────────────────
            r2 = subprocess.run(
                ["git", "status", "--porcelain"],
                capture_output=True, cwd=repo_dir, timeout=10,
            )
            for line in r2.stdout.decode("utf-8", errors="replace").splitlines():
                if len(line) > 3:
                    # "XY path" or "XY old -> new" (renames)
                    path_part = line[3:].strip()
                    parts = path_part.split(" -> ")
                    changed.add(parts[-1].strip().replace("\\", "/"))

        except Exception:
            return None

        return changed

    def smart_update(
        self,
        repo_path: str,
        current_book: str,
        last_analyzed: str,
        company_context: str = "A software project",
        output_dir: str = "books",
        on_progress=None,
    ) -> dict:
        """
        Incremental update: find files with real changes since last_analyzed
        and ask the AI to patch only the affected sections of the current Memory Bank.

        Change detection priority:
          1. Git (committed + uncommitted) — precise, ignores mtime noise
          2. mtime fallback — for non-git repos

        Returns:
          {"status": "no_changes"}            — nothing changed
          {"status": "draft", "path": "..."}  — draft saved, ready to diff/apply
        """
        def progress(msg):
            if on_progress:
                on_progress(msg)

        from datetime import datetime as _dt

        try:
            last_ts = _dt.fromisoformat(last_analyzed).timestamp() if last_analyzed else None
        except Exception:
            last_ts = None   # unparseable — skip git, mtime will catch everything

        # ── Crawl (no AI, fast) ──────────────────────────────────────
        def _fmt_ts(iso):
            try:
                return _dt.fromisoformat(iso).strftime("%d %b %Y")
            except Exception:
                return "initial analysis"

        progress(f"Scanning for changes since {_fmt_ts(last_analyzed)}…")
        progress("Crawling repository files…")
        crawler = RepoCrawler(repo_path, self.config_path)
        data = crawler.crawl()

        project_name = data["name"]
        all_files: dict = data["files"]   # {relative_path: {content, size, ...}}
        progress(f"Found {len(all_files)} files. Detecting changes…")

        repo_root = Path(repo_path)
        git_root  = str(repo_root) if repo_root.is_dir() else str(repo_root.parent)

        # ── Detect changed + deleted files ───────────────────────────
        # `changed` = files that exist now and were modified/added
        # `deleted` = files that no longer exist but were touched (git) or
        #             whose parent directory changed (mtime)
        import os as _os
        changed: dict = {}
        deleted: list = []
        cmp_ts   = last_ts if last_ts is not None else 0.0
        scan_root = repo_root if repo_root.is_dir() else repo_root.parent
        existing_paths = {rel.replace("\\", "/") for rel in all_files}

        git_changed = self._get_git_changed_files(git_root, last_ts) if last_ts else None

        if git_changed is not None:
            # ── Git path ─────────────────────────────────────────────
            # Files in git_changed that still exist → modified/added
            # Files in git_changed that are gone   → deleted
            for rel_norm in git_changed:
                if rel_norm in existing_paths:
                    # find original key (may use backslashes on Windows)
                    key = next((k for k in all_files if k.replace("\\", "/") == rel_norm), None)
                    if key:
                        changed[key] = all_files[key]
                else:
                    deleted.append(rel_norm)
            method = "git"
        else:
            # ── mtime path ───────────────────────────────────────────
            # Dirs whose mtime changed = something was added or deleted inside
            dirs_changed: set = set()
            for dirpath_str, dirnames, _ in _os.walk(str(scan_root)):
                dirnames[:] = [d for d in dirnames
                               if d not in getattr(crawler, "ignore_dirs", set())]
                try:
                    if Path(dirpath_str).stat().st_mtime > cmp_ts:
                        dirs_changed.add(str(Path(dirpath_str).resolve()))
                except OSError:
                    pass

            for rel_path, info in all_files.items():
                abs_path = (scan_root / rel_path).resolve()
                try:
                    if (abs_path.stat().st_mtime > cmp_ts or
                            str(abs_path.parent) in dirs_changed):
                        changed[rel_path] = info
                except OSError:
                    pass

            # For mtime we can't know exact deleted filenames — but we can
            # extract filenames referenced in the current book and check which
            # ones no longer exist on disk.  A simple heuristic: any token that
            # looks like a filename (has an extension) mentioned in the book but
            # absent from the current file tree.
            if dirs_changed and current_book:
                import re as _re
                book_files = set(_re.findall(r'[\w\-./]+\.\w{1,6}', current_book))
                for bf in book_files:
                    bf_norm = bf.replace("\\", "/").lstrip("./")
                    if bf_norm and bf_norm not in existing_paths:
                        # Only flag it if its parent dir actually changed
                        candidate = (scan_root / bf_norm)
                        if str(candidate.parent.resolve()) in dirs_changed:
                            deleted.append(bf_norm)

            method = "mtime"

        if not changed and not deleted:
            return {"status": "no_changes"}

        summary_parts = []
        if changed: summary_parts.append(f"{len(changed)} modified/added")
        if deleted:  summary_parts.append(f"{len(deleted)} deleted")
        progress(f"Detected {', '.join(summary_parts)} since {_fmt_ts(last_analyzed)} [{method}]. Updating Memory Bank…")

        # ── Build targeted prompt ─────────────────────────────────────
        changed_content = self._format_files(changed) if changed else "(none)"
        deleted_section = (
            "\n".join(f"- `{f}`" for f in sorted(set(deleted)))
            if deleted else "(none)"
        )
        last_dt_str = _fmt_ts(last_analyzed)

        prompt = f"""You are updating an existing Memory Bank for the project **{project_name}**.

## Current Memory Bank

{current_book}

---

## Files modified or added since {last_dt_str}

{changed_content}

## Files deleted since {last_dt_str}

{deleted_section}

---

## Instructions

Update the Memory Bank to accurately reflect the current state of the project.

Rules:
- Keep every section that is NOT affected by these changes exactly as-is — word for word.
- Update only sections genuinely impacted by the changed or deleted files.
- For modified/added files: update descriptions, APIs, workflows, and any affected sections.
- For deleted files: remove all references to them throughout the document.
- If new files introduce new concepts or APIs, add the relevant sections.
- Update the "Last updated" date at the top to today.
- Do NOT rewrite unaffected sections — surgical edits only.
- Preserve existing Markdown formatting and section headings.

Output the complete updated Memory Bank (all sections, not just the changed parts).
"""

        prompt_size = len(prompt)
        model_name = self.model.model
        if "ollama" in model_name.lower():
            progress(f"Sending to local model ({model_name.split('/')[-1]}) — {prompt_size:,} chars. This may take a few minutes…")
        else:
            progress(f"Sending to AI ({prompt_size:,} chars)…")

        new_content = self._call_with_retry(SYSTEM_PROMPT, prompt, "Applying updates…")
        progress("AI response received. Saving draft…")
        new_content = self._enforce_header(new_content, project_name)

        # ── Save as draft ─────────────────────────────────────────────
        books_path = Path(output_dir)
        books_path.mkdir(parents=True, exist_ok=True)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        draft_path = books_path / f"{safe_name}_draft.md"
        draft_path.write_text(new_content, encoding="utf-8")

        return {"status": "draft", "path": str(draft_path)}

    def draft_update(
        self,
        repo_path: str,
        company_context: str = "Auto-draft from file change",
        output_dir: str = "books",
        on_progress=None,
    ) -> str:
        """
        Generate a new Memory Bank and save it as a draft (not applied yet).
        User reviews via `memoria review` and approves or rejects.
        Returns path to the draft file.
        """
        def progress(msg):
            if on_progress:
                on_progress(msg)

        progress("Crawling repository...")
        crawler = RepoCrawler(repo_path, self.config_path)
        data = crawler.crawl()

        project_name = data["name"]
        structure = data["structure"]
        files = data["files"]
        files_content = self._format_files(files)
        total_chars = len(files_content)

        if total_chars <= self.CHUNK_THRESHOLD:
            progress(f"Analysing {data['stats']['total_files']} files...")
            new_content = self._generate_single(
                project_name, company_context, structure, files_content, files
            )
        else:
            progress(f"Large repo — chunking ({total_chars // 1000}K chars)...")
            new_content = self._generate_chunked(
                project_name, company_context, structure, crawler, on_progress, files
            )

        # Save as draft, not as the live book
        books_path = Path(output_dir)
        books_path.mkdir(parents=True, exist_ok=True)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        draft_path = books_path / f"{safe_name}_draft.md"
        draft_path.write_text(new_content, encoding="utf-8")

        return str(draft_path)

    def apply_draft(self, project_name: str, output_dir: str = "books") -> str:
        """Apply a pending draft — archives current book, promotes draft to live."""
        books_path = Path(output_dir)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        draft_path = books_path / f"{safe_name}_draft.md"

        if not draft_path.exists():
            raise FileNotFoundError(f"No draft found for '{project_name}'. Expected: {draft_path}")

        draft_content = draft_path.read_text(encoding="utf-8")
        live_path = self._save_book(project_name, draft_content, output_dir)
        draft_path.unlink()  # Remove draft after applying
        return live_path

    def reject_draft(self, project_name: str, output_dir: str = "books"):
        """Discard a pending draft — live book is untouched."""
        books_path = Path(output_dir)
        safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
        draft_path = books_path / f"{safe_name}_draft.md"

        if not draft_path.exists():
            raise FileNotFoundError(f"No draft found for '{project_name}'.")

        draft_path.unlink()

    def _enforce_header(self, content: str, project_name: str) -> str:
        """
        Guarantee the first two lines are always correct — date and model.
        Replaces whatever the AI wrote there so it can never hallucinate the header.
        """
        correct_header = (
            f"# {project_name} — Memory Bank\n"
            f"> Last updated: {datetime.now().strftime('%Y-%m-%d')} | "
            f"Generated by Memoria ({self.model.model})"
        )
        lines = content.splitlines()
        # Find where the real content starts (skip any AI-written title/subtitle)
        start = 0
        for i, line in enumerate(lines):
            if line.startswith("---") or line.startswith("## "):
                start = i
                break
        body = "\n".join(lines[start:])
        return f"{correct_header}\n\n{body}"

    def _call_with_retry(self, system: str, prompt: str, progress_msg: str = "") -> str:
        """
        Shared retry wrapper.
        - [AUTH]      → fail immediately, clear message about key/creds
        - [RATELIMIT] → retry once (15s wait), then fail with quota message
        - [TRANSIENT] → retry once (15s wait), then re-raise
        - [ERROR]     → fail immediately
        """
        for attempt in range(2):
            try:
                return self.model.complete(system, prompt)
            except RuntimeError as e:
                err = str(e)
                tag = err.split("]")[0].lstrip("[") if err.startswith("[") else "ERROR"

                if tag == "AUTH":
                    raise RuntimeError(
                        "Authentication failed — your API key or credentials are invalid.\n"
                        "• Check your key in ~/.memoria/.env\n"
                        "• For AWS: verify AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, "
                        "AWS_REGION_NAME\n"
                        "• Run `memoria init` to reconfigure"
                    ) from e

                if tag in ("RATELIMIT", "TRANSIENT") and attempt == 0:
                    time.sleep(15)
                    continue

                if tag == "RATELIMIT":
                    raise RuntimeError(
                        "Rate limit hit and retry failed. "
                        "Your API quota may be exhausted. "
                        "Wait a few minutes, check your quota, or switch model."
                    ) from e

                raise
