"""
memoria interview — Guided CLI Q&A that extracts process knowledge from a subject-matter expert
and synthesises the transcript into a structured Process Memory Bank.

Flow:
  1. Ask a base set of questions about the process
  2. After each answer, decide (via LLM) whether to probe deeper
  3. When the interview ends, synthesise all Q&A into a Process Memory Bank
"""

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import ModelProvider

# ── Base question sequence ────────────────────────────────────────────────────

BASE_QUESTIONS = [
    (
        "trigger",
        "What triggers this process? What event, condition, or signal starts it? "
        "(e.g. a customer complaint, a new hire joining, an alert firing)"
    ),
    (
        "overview",
        "Give me a high-level overview. What does this process do from start to finish "
        "in 2–3 sentences?"
    ),
    (
        "steps",
        "Walk me through the steps in order. What happens first, then what? "
        "Go as granular as you like — I'll ask follow-ups."
    ),
    (
        "decisions",
        "Are there any decision points where the path forks? "
        "(e.g. 'If X is true, we do A — otherwise we do B')"
    ),
    (
        "roles",
        "Who is involved? For each step, who does it — is it one person, a team, "
        "or does it depend? What role or job title?"
    ),
    (
        "tools",
        "What tools, systems, or access do people need to run this process? "
        "(e.g. Jira, Slack, AWS console, a spreadsheet, a specific dashboard)"
    ),
    (
        "exceptions",
        "What are the common exceptions or things that can go wrong? "
        "How are they handled?"
    ),
    (
        "escalation",
        "When something is out of scope or goes badly wrong, who do you escalate to? "
        "How do you contact them? Is there an SLA?"
    ),
    (
        "frequency",
        "How often does this process run? How long does it typically take "
        "from trigger to completion?"
    ),
    (
        "verification",
        "When was this last tested or done in a real situation? "
        "Are there any known gaps or steps that are undocumented?"
    ),
]

# ── Prompts ───────────────────────────────────────────────────────────────────

_FOLLOWUP_SYSTEM = """You are an expert process interviewer. A subject-matter expert is describing
a business process. Your job is to ask the single most useful follow-up question based on their
latest answer.

Rules:
- Only ask a follow-up if the answer is genuinely incomplete or raises an unanswered question
- If the answer is thorough, return exactly: NO_FOLLOWUP
- Ask ONE specific question — not multiple questions in one
- Be conversational, not formal. You're having a dialogue.
- Never repeat a question that was already asked."""

_FOLLOWUP_PROMPT = """The interviewer just asked:
QUESTION: {question}

The expert answered:
ANSWER: {answer}

Should we probe deeper? If yes, return a single follow-up question.
If the answer is complete, return exactly: NO_FOLLOWUP"""

_SYNTHESIS_SYSTEM = """You are an expert business process analyst. You have just conducted an
interview with a subject-matter expert about a process or workflow. Your job is to turn the
interview transcript into a structured Process Memory Bank.

Rules:
- Synthesize the answers — don't just quote them verbatim
- Infer implicit steps from the expert's answers
- Structure everything clearly so someone who was not in the interview can follow the process
- Flag gaps honestly — if something was unclear, say so
- Write for both a human doing this for the first time AND an AI agent following instructions
"""

_SYNTHESIS_PROMPT = """Below is a full interview transcript about a process.
Synthesize it into a structured Process Memory Bank.

PROCESS TOPIC: {topic}
PROJECT / TEAM: {project}
DATE: {date}

INTERVIEW TRANSCRIPT:
{transcript}

Write the Process Memory Bank using EXACTLY this structure:

# {topic} — Process Memory Bank
> Last updated: {date} | Generated by Memoria ({model}) | Type: process
> *Source: Expert interview*

---

## TL;DR
[3-5 bullets. What does this process do? Who runs it? When does it trigger? Key outcome.]

---

## Process Overview

| Field | Value |
|-------|-------|
| **Process Name** | {topic} |
| **Owner / DRI** | [From interview, or "Not specified"] |
| **Trigger** | [From interview] |
| **Scope** | [What is covered? What is excluded?] |
| **Frequency** | [From interview] |
| **Estimated Duration** | [From interview] |
| **Last Verified** | [From interview, or today's date if just documented] |
| **Confidence** | Medium — *Interview-sourced. Needs production verification.* |

---

## Step-by-Step Procedure

[Number every step. For each step include: action, who, tool, expected output, warnings.]

### Step 1: [Name]
**Who:** [Role or person]
**Tool:** [System or tool used]
**Action:** [Exactly what to do]
**Output:** [What should be true when this step is complete]

[Continue for each step...]

---

## Decision Points & Branching Logic

| Decision | Condition | If True → | If False → |
|----------|-----------|-----------|------------|

---

## Exceptions & Edge Cases

| Scenario | What to do differently |
|----------|------------------------|

---

## Escalation Paths

| Situation | Escalate To | How | SLA |
|-----------|-------------|-----|-----|

---

## Tools & Resources Required

- **Systems:** [List all tools and platforms]
- **Access needed:** [Permissions, credentials, accounts]
- **Dependencies:** [Other processes or teams that must act first]

---

## Confidence & Verification Status

| Section | Confidence | Source |
|---------|------------|--------|
| Full procedure | Medium | Expert interview — {date} |

**Overall confidence:** Medium — interview-sourced, not yet verified against production
**Gaps:** [Anything the expert flagged as unclear, incomplete, or not yet documented]

---

## Known Issues & Improvement Notes

[Things flagged during the interview as wrong, unclear, outdated, or improvable.]

---
"""


# ── Core interview engine ─────────────────────────────────────────────────────

def run_interview(
    topic: str,
    project: str,
    duration_minutes: int,
    config_path: str,
    books_dir: str,
    on_print=None,
    on_prompt=None,
) -> dict:
    """
    Run a full expert interview session.

    on_print(msg): called to display output (defaults to print)
    on_prompt(question) -> str: called to get user input (defaults to input())

    Returns a dict with:
      - transcript: list of {"question": ..., "answer": ...} dicts
      - output_path: where the Process Memory Bank was saved
      - duration_seconds: how long the interview took
    """
    def _print(msg):
        if on_print:
            on_print(msg)
        else:
            print(msg)

    def _prompt(question: str) -> str:
        if on_prompt:
            return on_prompt(question)
        return input(question)

    model = ModelProvider(config_path)
    start_time = time.time()
    deadline = start_time + (duration_minutes * 60)
    transcript = []
    asked_questions: set[str] = set()

    for section_key, base_question in BASE_QUESTIONS:
        # Time check
        if time.time() > deadline:
            _print("\n[dim]Time limit reached. Wrapping up...[/dim]")
            break

        # Skip if already covered via a previous follow-up
        if section_key in asked_questions:
            continue
        asked_questions.add(section_key)

        _print(f"\n[bold cyan]Q:[/bold cyan] {base_question}")
        answer = _prompt("  ▸ ").strip()
        if not answer:
            answer = "(no answer provided)"
        if answer.lower() in ("done", "finish", "exit", "quit"):
            _print("[dim]Ending interview early.[/dim]")
            transcript.append({"question": base_question, "answer": answer})
            break

        transcript.append({"question": base_question, "answer": answer})

        # Adaptive follow-up
        if time.time() < deadline and len(answer.split()) >= 5:
            try:
                followup_raw = model.complete(
                    _FOLLOWUP_SYSTEM,
                    _FOLLOWUP_PROMPT.format(question=base_question, answer=answer),
                )
                followup = followup_raw.strip()
                if followup and followup.upper() != "NO_FOLLOWUP" and len(followup) > 10:
                    _print(f"\n  [dim]Follow-up:[/dim] {followup}")
                    fu_answer = _prompt("  ▸ ").strip()
                    if fu_answer and fu_answer.lower() not in ("skip", "done", "exit", "quit"):
                        transcript.append({"question": followup, "answer": fu_answer})
                        if fu_answer.lower() in ("done", "finish"):
                            break
            except Exception:
                pass  # follow-up generation is best-effort, never block the interview

    elapsed = int(time.time() - start_time)

    # Synthesize
    _print("\n[dim]Synthesizing process documentation...[/dim]")
    transcript_text = "\n\n".join(
        f"Q: {item['question']}\nA: {item['answer']}"
        for item in transcript
    )

    book_content = model.complete(
        _SYNTHESIS_SYSTEM,
        _SYNTHESIS_PROMPT.format(
            topic=topic,
            project=project,
            date=datetime.now().strftime("%Y-%m-%d"),
            transcript=transcript_text,
            model=model.model,
        ),
    )

    # Ensure the Type: process tag is present
    import re as _re
    if "| Type:" not in book_content:
        book_content = _re.sub(
            r"(\| Generated by Memoria \([^)]+\))",
            r"\1 | Type: process",
            book_content,
            count=1,
        )

    # Save
    books_path = Path(books_dir)
    books_path.mkdir(parents=True, exist_ok=True)
    archive_path = books_path / ".archive"
    archive_path.mkdir(exist_ok=True)

    safe_topic = "".join(c if c.isalnum() or c in "-_" else "_" for c in topic)
    book_file = books_path / f"{safe_topic}_memory_bank.md"

    if book_file.exists():
        prev_mtime = datetime.fromtimestamp(book_file.stat().st_mtime)
        archive_name = f"{safe_topic}_{prev_mtime.strftime('%Y%m%d_%H%M%S')}.md"
        book_file.rename(archive_path / archive_name)

    book_file.write_text(book_content, encoding="utf-8")

    # Index into vector search
    try:
        from .search import index_book
        index_book(safe_topic, book_content, books_dir)
    except Exception:
        pass

    return {
        "transcript": transcript,
        "output_path": str(book_file),
        "duration_seconds": elapsed,
    }
