"""
Org-level Memory Bank — synthesises all individual project Memory Banks into
one authoritative meta-book that describes the entire organisation.

  memoria org              — build the org book from all Memory Banks
  memoria org --output     — print to stdout (json | markdown | terminal)
  memoria org --rebuild    — force rebuild even if org book is recent

Output file: <books_dir>/_org_memory_bank.md

──────────────────────────────────────────────────────────────────────────────
What the Org Book Contains
──────────────────────────────────────────────────────────────────────────────

  1. Organisation TL;DR      — 5 bullets; what the org does end-to-end
  2. Tech Landscape          — languages, frameworks, infra across all projects
  3. Project Directory       — every project, one paragraph each
  4. Cross-project Map       — dependencies, shared libraries, common patterns
  5. Risk Radar              — tech-debt hotspots, stale books, single points of failure
  6. Onboarding Path         — recommended reading order for a new engineer
  7. Open Questions          — gaps, undocumented systems, conflicting decisions

For large orgs (> 8 books) we first produce a compact "digest" of each book
(~400 chars) and synthesise from those, keeping well within context limits.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional


# ─── Constants ────────────────────────────────────────────────────────────────

ORG_BOOK_NAME   = "Organisation_memory_bank.md"  # capital O → sorts near top; displays as "Organisation" in UI
COMPACT_LIMIT   = 1_600   # chars per book when building compact digests
FULL_LIMIT      = 6_000   # chars per book when number of books is small
SMALL_ORG_SIZE  = 8       # use full excerpts when #books ≤ this


# ─── Org prompt ───────────────────────────────────────────────────────────────

_ORG_SYSTEM = """\
You are a principal engineer who has read every project's Memory Bank in this
organisation. You understand how the projects relate, what tech is used where,
and where the bodies are buried.

Write an Org-level Memory Bank — the single document that gives any engineer,
manager, or AI assistant a complete picture of the entire organisation.

Rules:
- Be specific. Name real project names, real technologies, real risks.
- Draw connections between projects. Note dependencies and shared patterns.
- Surface risks honestly — stale docs, single points of failure, hidden coupling.
- Write for two audiences: a new hire on day 1, and an AI about to make a change.
"""

_ORG_PROMPT = """\
Today's date: {date}
Organisation has {n_projects} projects.

PROJECT SUMMARIES:
{summaries}

Write the Org-level Memory Bank using EXACTLY this structure:

# Organisation Memory Bank
> Generated by Memoria on {date} | {n_projects} projects synthesised

---

## TL;DR
[5 bullet points. What does this organisation BUILD, end to end?
 What are its core capabilities? What does it use to build them?]

---

## 1. Tech Landscape
[Languages, frameworks, databases, infrastructure, third-party services.
 Which projects use what? Where does the team have deep expertise vs surface knowledge?]

## 2. Project Directory
[Every project — one crisp paragraph each.
 What it does, who depends on it, and the one thing you must know before touching it.]

## 3. Cross-project Map
[How do the projects connect? What calls what? What shares a database or message bus?
 What would a change to Project X break in Project Y?
 Use a simple text diagram if it helps.]

## 4. Risk Radar
[Honest assessment of the organisation's technical health.
 Which projects carry the most risk? What's undocumented? What has no tests?
 What would bring everything down if it failed? Severity: critical / high / medium]

## 5. Onboarding Path
[Recommended reading order for a new engineer.
 Start with X because it's the core. Then read Y to understand the data layer. Etc.]

## 6. Open Questions
[Things that are unclear, undocumented, or inconsistently decided across projects.
 These are gaps the team should fill.]

---
"""


# ─── Book loading + extraction ────────────────────────────────────────────────

def _list_books(books_dir: str) -> list[Path]:
    """Return all project Memory Bank files (excludes the org book and draft files)."""
    d = Path(books_dir)
    return sorted(
        p for p in d.glob("*_memory_bank.md")
        if p.name != ORG_BOOK_NAME
        and not p.name.endswith("_draft.md")
    )


def _extract_project_name(book: Path) -> str:
    """Derive human-readable project name from filename."""
    stem = book.stem.replace("_memory_bank", "")
    return stem.replace("_", " ").replace("-", " ").strip()


def _extract_section(text: str, heading: str, max_chars: int = 800) -> str:
    """
    Extract a section by heading keyword (case-insensitive).
    Returns up to max_chars of that section's content.
    """
    pattern = re.compile(
        r"^#{1,3}\s+.*?" + re.escape(heading) + r".*?\n(.*?)(?=^#{1,3}\s|\Z)",
        re.IGNORECASE | re.MULTILINE | re.DOTALL,
    )
    m = pattern.search(text)
    if m:
        content = m.group(1).strip()
        return content[:max_chars]
    return ""


def _compact_digest(name: str, text: str, max_chars: int = COMPACT_LIMIT) -> str:
    """
    Build a compact digest of a Memory Bank for use in large-org synthesis.
    Tries to pull TL;DR + Architecture sections; falls back to first N chars.
    """
    tldr = _extract_section(text, "TL;DR", 400)
    arch = _extract_section(text, "Architecture", 400)
    what = _extract_section(text, "What This Project Does", 300)

    parts = [f"### {name}"]
    if tldr:
        parts.append(f"**TL;DR:**\n{tldr}")
    if what and not tldr:
        parts.append(f"**Overview:**\n{what[:300]}")
    if arch:
        parts.append(f"**Architecture:**\n{arch}")
    if not tldr and not arch:
        # Fallback — first meaningful paragraph
        parts.append(text[:max_chars])

    digest = "\n\n".join(parts)
    return digest[:max_chars]


def _full_excerpt(name: str, text: str, max_chars: int = FULL_LIMIT) -> str:
    """Full excerpt for small orgs — includes more context."""
    return f"### {name}\n\n{text[:max_chars]}"


def build_summaries(books_dir: str) -> tuple[list[dict], str]:
    """
    Read all Memory Banks and build a summaries block for the LLM prompt.

    Returns:
      (project_list, summaries_text)
      project_list — [{name, path, chars}]
      summaries_text — ready to inject into the org prompt
    """
    books = _list_books(books_dir)
    if not books:
        return [], ""

    projects = []
    excerpts  = []
    small_org = len(books) <= SMALL_ORG_SIZE

    for book in books:
        text = book.read_text(encoding="utf-8")
        name = _extract_project_name(book)
        if small_org:
            snippet = _full_excerpt(name, text, FULL_LIMIT)
        else:
            snippet = _compact_digest(name, text, COMPACT_LIMIT)
        excerpts.append(snippet)
        projects.append({"name": name, "path": str(book), "chars": len(text)})

    return projects, "\n\n---\n\n".join(excerpts)


# ─── Synthesis ────────────────────────────────────────────────────────────────

def build_org_book(
    config_path: str | None = None,
    books_dir:   str | None = None,
    on_progress=None,
) -> str:
    """
    Synthesise all Memory Banks into an org-level book.

    Returns the path to the written org book file.
    Raises RuntimeError on model/config errors (same as BookGenerator).
    """
    from .models import ModelProvider

    def progress(msg: str):
        if on_progress:
            on_progress(msg)

    # ── Resolve paths ─────────────────────────────────────────────────────────
    if not books_dir:
        from pathlib import Path as _P
        books_dir = str(_P.home() / ".memoria" / "books")
    Path(books_dir).mkdir(parents=True, exist_ok=True)

    if not config_path:
        cfg_candidate = Path.home() / ".memoria" / "config.yaml"
        config_path = str(cfg_candidate) if cfg_candidate.exists() else ""

    # ── Load Memory Banks ─────────────────────────────────────────────────────
    progress("Reading Memory Banks…")
    projects, summaries = build_summaries(books_dir)
    if not projects:
        raise ValueError(
            "No Memory Banks found in the books directory. "
            "Run `memoria analyze` on at least one project first."
        )
    progress(f"Found {len(projects)} Memory Bank(s). Building org synthesis…")

    # ── Model ─────────────────────────────────────────────────────────────────
    model = ModelProvider(config_path)

    # ── Prompt ────────────────────────────────────────────────────────────────
    date_str = datetime.now().strftime("%Y-%m-%d")
    prompt   = _ORG_PROMPT.format(
        date       = date_str,
        n_projects = len(projects),
        summaries  = summaries,
    )

    progress(f"Sending {len(projects)} project digest(s) to {model.model}…")

    # ── LLM call with retry ────────────────────────────────────────────────────
    _ATTEMPTS = 3
    last_err  = None
    content   = None
    for attempt in range(_ATTEMPTS):
        try:
            import litellm
            response = litellm.completion(
                model      = model.model,
                messages   = [
                    {"role": "system",  "content": _ORG_SYSTEM},
                    {"role": "user",    "content": prompt},
                ],
                max_tokens = 4000,
                timeout    = 180,
            )
            content = response.choices[0].message.content.strip()
            break
        except Exception as exc:
            last_err = exc
            err_str  = str(exc).lower()
            if "rate" in err_str or "429" in err_str:
                import time
                wait = 15 * (attempt + 1)
                progress(f"Rate-limited — waiting {wait}s…")
                time.sleep(wait)
            elif attempt < _ATTEMPTS - 1:
                import time
                time.sleep(5)

    if content is None:
        raise RuntimeError(f"LLM call failed after {_ATTEMPTS} attempts: {last_err}")

    # ── Ensure correct header ─────────────────────────────────────────────────
    if not content.lstrip().startswith("# Organisation Memory Bank"):
        content = (
            f"# Organisation Memory Bank\n"
            f"> Generated by Memoria on {date_str} | {len(projects)} projects synthesised\n\n"
            f"---\n\n"
        ) + content

    # ── Write ─────────────────────────────────────────────────────────────────
    out_path = Path(books_dir) / ORG_BOOK_NAME
    out_path.write_text(content, encoding="utf-8")
    progress(f"Org book written → {out_path}")

    return str(out_path)


# ─── Helpers for CLI output ───────────────────────────────────────────────────

def render_org_terminal(org_path: str, console) -> None:
    """Pretty-print the org book in the terminal using Rich Markdown."""
    from rich.markdown import Markdown
    text = Path(org_path).read_text(encoding="utf-8")
    console.print(Markdown(text))


def render_org_json(projects: list[dict], org_path: str) -> dict:
    """Return a structured dict suitable for JSON output."""
    return {
        "org_book": org_path,
        "projects": projects,
        "generated_at": datetime.now().isoformat(),
    }
