"""
Shared fixtures and helpers for all Memoria tests.

Mock strategy
─────────────
Most tests mock litellm.completion so they run instantly without API keys.
Tests that need real AI are in tests/integration/test_user_fixtures.py
and are skipped automatically unless the MEMORIA_TEST_LIVE env var is set.

Fixture files
─────────────
tests/fixtures/          — static test data
  sample.ipynb           — Jupyter notebook (committed)
  sample.html            — HTML document (committed)
  README.md              — instructions for user-provided files (pdf/audio/image)
  sample.pdf             — DROP YOUR OWN (any short PDF)
  sample.m4a             — DROP YOUR OWN (any short audio file)
  sample.png             — DROP YOUR OWN (any image)
"""

import json
import os
import textwrap
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ─── Mock AI response ─────────────────────────────────────────────────────────

MOCK_BOOK_CONTENT = textwrap.dedent("""\
    # Test Project — Memory Bank
    > Last updated: 2024-01-01 | Generated by Memoria (mock-model)

    ---

    ## TL;DR
    - A test project used to verify Memoria works correctly
    - Uses Python, has a simple structure
    - No real functionality — purely for testing

    ---

    ## 1. What This Project Does
    A mock project for testing purposes.

    ## 2. Architecture — How It Works
    Simple two-file structure with no dependencies.

    ## 3. File & Module Map
    `main.py` — entry point
    `utils.py` — helpers

    ## 4. Key Concepts & Data Models
    None — this is a test fixture.

    ## 5. How to Run Locally
    ```bash
    python main.py
    ```

    ## 6. Common Workflows
    Run the tests.

    ## 7. Non-Obvious Decisions & Gotchas
    None.

    ## 8. What's Broken / Missing / Next
    Everything — this is a mock.
""")

MOCK_DOCUMENT_CONTENT = textwrap.dedent("""\
    # Test Documents — Memory Bank
    > Last updated: 2024-01-01 | Generated by Memoria (mock-model)

    ---

    ## TL;DR
    - A test document collection
    - Contains sample files for testing extraction

    ---

    ## 1. What This Collection Is About
    Test documents for Memoria's extraction pipeline.

    ## 2. Key Topics & Sections
    Testing, extraction, fixtures.

    ## 3. Important Data & Facts
    - Created for test purposes
    - No real data

    ## 4. Conclusions & Recommendations
    Tests pass.

    ## 5. Open Questions & Gaps
    None.

    ## 6. Quick Reference
    - Test fixture
""")


def make_mock_completion(content: str = MOCK_BOOK_CONTENT):
    """Return a mock litellm.completion response with the given content."""
    mock_response = MagicMock()
    mock_response.choices = [MagicMock()]
    mock_response.choices[0].message.content = content
    mock_response.usage = MagicMock()
    mock_response.usage.prompt_tokens = 100
    mock_response.usage.completion_tokens = 200
    return mock_response


# ─── Common pytest fixtures ───────────────────────────────────────────────────

@pytest.fixture
def tmp_books(tmp_path):
    """A temporary books output directory."""
    books = tmp_path / "books"
    books.mkdir()
    return books


@pytest.fixture
def tmp_config(tmp_path):
    """A minimal config.yaml in a temp directory."""
    cfg = tmp_path / "config.yaml"
    cfg.write_text(
        'model: "gemini/gemini-2.0-flash"\n'
        'max_tokens_output: 4000\n'
        'max_tokens_per_file: 2000\n',
        encoding="utf-8",
    )
    return cfg


@pytest.fixture
def sample_code_project(tmp_path):
    """A tiny Python project with 3 files — enough for the crawler."""
    proj = tmp_path / "my_project"
    proj.mkdir()

    (proj / "main.py").write_text(
        "from utils import greet\n\ndef main():\n    print(greet('world'))\n\nif __name__ == '__main__':\n    main()\n",
        encoding="utf-8",
    )
    (proj / "utils.py").write_text(
        "def greet(name: str) -> str:\n    return f'Hello, {name}!'\n",
        encoding="utf-8",
    )
    (proj / "requirements.txt").write_text("click>=8.0\nrich>=13.0\n", encoding="utf-8")
    (proj / "README.md").write_text("# My Project\nA simple greeting tool.\n", encoding="utf-8")
    return proj


@pytest.fixture
def sample_doc_folder(tmp_path):
    """A folder of documents (DOCX + XLSX) created programmatically."""
    folder = tmp_path / "documents"
    folder.mkdir()

    # Create a minimal DOCX
    try:
        from docx import Document
        doc = Document()
        doc.add_heading("Test Report", 0)
        doc.add_paragraph("This is a test document created for Memoria testing.")
        doc.add_heading("Section 1", 1)
        doc.add_paragraph("Content of section one.")
        doc.save(str(folder / "report.docx"))
    except ImportError:
        (folder / "report.txt").write_text("Test report\nContent here.", encoding="utf-8")

    # Create a minimal XLSX
    try:
        from openpyxl import Workbook
        wb = Workbook()
        ws = wb.active
        ws.title = "Data"
        ws.append(["Name", "Score", "Status"])
        ws.append(["Alice", 95, "Pass"])
        ws.append(["Bob", 72, "Pass"])
        ws.append(["Charlie", 45, "Fail"])
        wb.save(str(folder / "scores.xlsx"))
    except ImportError:
        (folder / "scores.csv").write_text("Name,Score,Status\nAlice,95,Pass\n", encoding="utf-8")

    return folder


@pytest.fixture
def mock_litellm():
    """Patch litellm.completion to avoid real API calls."""
    with patch("litellm.completion", return_value=make_mock_completion()) as mock:
        yield mock


@pytest.fixture
def mock_litellm_document():
    """Patch litellm.completion to return a document-style book."""
    with patch("litellm.completion", return_value=make_mock_completion(MOCK_DOCUMENT_CONTENT)) as mock:
        yield mock
