"""
Playwright conftest for Memoria UI tests.

Strategy
────────
Each test session spins up a real uvicorn server against a temp books_dir
with pre-seeded Memory Bank files. litellm.completion is monkeypatched at
the module level to return deterministic streaming SSE responses, so no
API keys are required.

Fixtures
────────
  live_server   — starts uvicorn on a random port; yields base URL
  page          — Playwright Page object navigated to the UI URL
  books_dir     — temp directory pre-seeded with 2 Memory Bank files
  mock_llm      — patches litellm.completion for all UI test SSE calls

Usage
─────
  pytest tests/ui/ --headed              # see the browser
  pytest tests/ui/ -k test_chat          # run one file
  pytest tests/ui/ --slowmo 200          # slow down interactions

Requirements
────────────
  pip install -r requirements-dev.txt
  playwright install chromium

Note
────
These tests are skipped automatically if playwright is not installed.
Enable them by running:  pytest tests/ui/ --run-ui
(configured via the --run-ui flag registered below)
"""

import json
import textwrap
import threading
import time
from pathlib import Path
from typing import Generator
from unittest.mock import MagicMock, patch

import pytest

# ── Skip guard ────────────────────────────────────────────────────────────────

def pytest_addoption(parser):
    parser.addoption(
        "--run-ui",
        action="store_true",
        default=False,
        help="Run Playwright UI tests (requires: pip install playwright; playwright install chromium)",
    )


def pytest_collection_modifyitems(config, items):
    if not config.getoption("--run-ui"):
        skip = pytest.mark.skip(reason="Pass --run-ui to run Playwright tests")
        for item in items:
            if "tests/ui" in str(item.fspath) or "tests\\ui" in str(item.fspath):
                item.add_marker(skip)


# ── Deterministic mock LLM responses ─────────────────────────────────────────

_MOCK_BOOK_AUTH = textwrap.dedent("""\
    # auth-service — Memory Bank
    > Last updated: 2026-01-01 | Generated by Memoria (test)

    ## TL;DR
    - Handles authentication via JWT tokens and OAuth2
    - FastAPI backend, Python 3.11
    - Rate limit: 100 requests/second

    ## Architecture
    Single FastAPI app with JWT middleware.
    Endpoints: /login, /logout, /refresh, /me

    ## Tech Stack
    Python, FastAPI, JWT, OAuth2, Redis (session store)

    ## Key Components
    `auth/routes.py` — login/logout endpoints
    `auth/jwt.py` — token generation and validation
    `auth/middleware.py` — request authentication check

    ## Common Workflows
    1. `POST /login` with credentials → JWT access token + refresh token
    2. Include `Authorization: Bearer <token>` on protected endpoints
    3. `POST /refresh` with refresh token → new access token

    ## Known Issues
    - Rate limiting triggers at 100 req/s; plan for bursts
    - Refresh tokens do not expire until revoked
""")

_MOCK_BOOK_PAYMENTS = textwrap.dedent("""\
    # payments-service — Memory Bank
    > Last updated: 2026-01-01 | Generated by Memoria (test)

    ## TL;DR
    - Processes card payments via Stripe
    - Depends on auth-service for user identity
    - PostgreSQL for transaction records

    ## Architecture
    FastAPI service calling Stripe API.
    Webhooks for async payment events.

    ## Tech Stack
    Python, FastAPI, Stripe, PostgreSQL, SQLAlchemy

    ## Key Components
    `payments/routes.py` — charge and refund endpoints
    `payments/stripe_client.py` — Stripe SDK wrapper
    `payments/models.py` — Transaction ORM model

    ## Known Issues
    - Stripe webhook signature validation sometimes fails on retries
""")


def _make_streaming_mock(text: str):
    """Return a mock litellm completion that streams the given text word by word."""
    words = text.split(" ")
    chunks = []
    for word in words:
        c = MagicMock()
        c.choices[0].delta.content = word + " "
        chunks.append(c)
    # Final chunk with None content
    final = MagicMock()
    final.choices[0].delta.content = None
    chunks.append(final)
    return chunks


def _mock_completion(*args, **kwargs):
    """Universal mock: detects stream=True and returns appropriate mock."""
    is_stream = kwargs.get("stream", False)
    messages  = kwargs.get("messages", [])

    # Pick a response based on the last user message content
    user_content = ""
    for m in reversed(messages):
        if m.get("role") == "user":
            user_content = m.get("content", "").lower()
            break

    if "oauth" in user_content or "auth" in user_content:
        text = "The auth-service uses OAuth2 and JWT tokens. Rate limit is 100 req/s."
    elif "payment" in user_content or "stripe" in user_content:
        text = "Payments go through Stripe. PostgreSQL stores transaction records."
    elif "plan" in user_content:
        text = json.dumps({
            "summary": "Plan touches auth-service and payments-service.",
            "affected_projects": ["auth-service", "payments-service"],
            "dependencies": [
                {"project": "auth-service", "relation": "OAuth2 tokens", "notes": "rate limit concern"}
            ],
            "risks": [
                {"severity": "high", "title": "Rate limit", "detail": "100 req/s cap", "source": "auth-service"}
            ],
            "prior_art": [],
            "recommended_actions": ["Run memoria ask --project auth-service"],
        })
    else:
        text = "This project uses Python and FastAPI. See the Memory Bank for full details."

    if is_stream:
        return _make_streaming_mock(text)
    else:
        mock = MagicMock()
        mock.choices[0].message.content = text
        return mock


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="session")
def books_dir(tmp_path_factory) -> Path:
    """Temp books directory with 2 pre-seeded Memory Banks."""
    bd = tmp_path_factory.mktemp("books")
    (bd / "auth_service_memory_bank.md").write_text(_MOCK_BOOK_AUTH,     encoding="utf-8")
    (bd / "payments_service_memory_bank.md").write_text(_MOCK_BOOK_PAYMENTS, encoding="utf-8")
    return bd


@pytest.fixture(scope="session")
def config_file(tmp_path_factory) -> Path:
    """Minimal config.yaml for the test server."""
    cfg = tmp_path_factory.mktemp("config") / "config.yaml"
    cfg.write_text(
        "model: gpt-4o-mini\n"
        "max_tokens: 512\n",
        encoding="utf-8",
    )
    return cfg


@pytest.fixture(scope="session")
def live_server(books_dir, config_file) -> Generator[str, None, None]:
    """
    Start a real uvicorn server for the duration of the test session.
    Yields the base URL (e.g. 'http://localhost:34521').
    """
    import socket
    import uvicorn

    # Find a free port
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        port = s.getsockname()[1]

    from memoria.ui import create_app
    app = create_app(
        config_path=str(config_file),
        books_dir=str(books_dir),
    )

    server = uvicorn.Server(uvicorn.Config(
        app=app,
        host="127.0.0.1",
        port=port,
        log_level="error",  # suppress uvicorn logs during tests
    ))

    thread = threading.Thread(target=server.run, daemon=True)

    with patch("litellm.completion", side_effect=_mock_completion):
        thread.start()
        # Wait for server to be ready
        base_url = f"http://127.0.0.1:{port}"
        for _ in range(30):
            try:
                import urllib.request
                urllib.request.urlopen(f"{base_url}/api/projects", timeout=1)
                break
            except Exception:
                time.sleep(0.2)
        else:
            pytest.fail("Test server did not start within 6 seconds")

        yield base_url

        server.should_exit = True
        thread.join(timeout=5)


@pytest.fixture(scope="session")
def mock_llm():
    """Session-scoped patch of litellm.completion for all UI tests."""
    with patch("litellm.completion", side_effect=_mock_completion) as m:
        yield m


@pytest.fixture
def page(live_server, browser):
    """
    Playwright page fixture that navigates to the UI before each test.
    Creates a new browser context and page, then navigates to the UI.
    """
    context = browser.new_context()
    _page = context.new_page()
    _page.goto(f"{live_server}/ui")
    # Wait for the app to boot (sidebar project list loaded)
    _page.wait_for_selector("#sidebar", timeout=10_000)
    yield _page
    context.close()


# ── Helpers ───────────────────────────────────────────────────────────────────

def wait_for_stream_done(page, selector: str, timeout: int = 15_000) -> str:
    """
    Wait until the element at `selector` stops changing content,
    indicating streaming has finished. Returns the final text content.

    Uses a polling loop: checks content every 300ms; exits when stable
    for 600ms or when timeout is reached.
    """
    import time as _time

    deadline = _time.time() + timeout / 1000
    last_text = ""
    stable_count = 0

    while _time.time() < deadline:
        try:
            current = page.locator(selector).inner_text()
        except Exception:
            current = ""
        if current == last_text and current:
            stable_count += 1
            if stable_count >= 2:   # stable for ~600ms
                return current
        else:
            stable_count = 0
        last_text = current
        _time.sleep(0.3)

    return last_text  # return whatever we have at timeout


def click_project(page, project_name: str):
    """Click a project in the sidebar by name (case-insensitive prefix match)."""
    page.locator(f".project-item[data-project]").filter(
        has_text=project_name
    ).first.click()


def switch_tab(page, tab_name: str):
    """Click a tab button by its data-tab attribute."""
    page.locator(f".tab[data-tab='{tab_name}']").click()
